import os
import json
import shutil

notebook_path = os.path.abspath(os.path.join("notebooks", "point_cloud_interactive_viewer.ipynb"))
fix_notebook_path = os.path.abspath(os.path.join("fix", "point_cloud_interactive_viewer.ipynb"))
os.makedirs(os.path.dirname(notebook_path), exist_ok=True)
os.makedirs(os.path.dirname(fix_notebook_path), exist_ok=True)

cells = []

# Cell 1: Install Dependencies
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_01_install_deps",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── Cài Đặt Thư Viện Đọc PLY, Xử Lý Ảnh & Biểu Diễn 3D Trực Quan ───────────────\n",
        "!pip install -q plyfile plotly numpy pandas matplotlib pillow"
    ]
})

# Cell 2: True Full-Width Pure Black 3D Interactive Point Cloud Visualizer
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_02_plotly_interactive_pcd",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── KHÂU 1: Hiển Thị Mây Điểm Ban Đầu (Iter 0) True Full-Width Nền Đen 3D ───────────\n",
        "import os\n",
        "import numpy as np\n",
        "from plyfile import PlyData\n",
        "import plotly.graph_objects as go\n",
        "from IPython.display import HTML, display\n",
        "\n",
        "def display_interactive_point_cloud_plotly(ply_path, max_points=50000):\n",
        "    \"\"\"\n",
        "    Hiển thị Khung Mây Điểm 3D Tương Tác Full-Width Nền Đen Tuyền (#000000).\n",
        "    - Tự động Ép Khung Width 100% tràn ngập toàn bộ ô Notebook trong VS Code.\n",
        "    - Nền Đen Tuyền (#000000) làm nổi bật toàn bộ các điểm mây 3D sắc nét.\n",
        "    - Nút '▶ Tự Động Quay 360°' và '⏸ Tạm Dừng' xoay mây điểm quanh tâm.\n",
        "    \"\"\"\n",
        "    if not os.path.exists(ply_path):\n",
        "        print(f\"❌ Không tìm thấy file point cloud tại: {ply_path}\")\n",
        "        return\n",
        "\n",
        "    print(f\"📂 Đang nạp Mây Điểm 3D Khâu 1: {ply_path} ...\")\n",
        "    plydata = PlyData.read(ply_path)\n",
        "    vertex = plydata['vertex']\n",
        "\n",
        "    x = np.asarray(vertex['x'], dtype=np.float32)\n",
        "    y = np.asarray(vertex['y'], dtype=np.float32)\n",
        "    z = np.asarray(vertex['z'], dtype=np.float32)\n",
        "\n",
        "    # Giải mã màu sắc từ thuộc tính PLY (Hỗ trợ cả PLY thường & 3DGS Spherical Harmonics)\n",
        "    names = [p.name for p in vertex.properties]\n",
        "    if 'red' in names and 'green' in names and 'blue' in names:\n",
        "        r = np.asarray(vertex['red'], dtype=np.float32)\n",
        "        g = np.asarray(vertex['green'], dtype=np.float32)\n",
        "        b = np.asarray(vertex['blue'], dtype=np.float32)\n",
        "        if r.max() > 1.0:\n",
        "            r, g, b = r / 255.0, g / 255.0, b / 255.0\n",
        "    elif 'f_dc_0' in names and 'f_dc_1' in names and 'f_dc_2' in names:\n",
        "        f_dc_0 = np.asarray(vertex['f_dc_0'], dtype=np.float32)\n",
        "        f_dc_1 = np.asarray(vertex['f_dc_1'], dtype=np.float32)\n",
        "        f_dc_2 = np.asarray(vertex['f_dc_2'], dtype=np.float32)\n",
        "        SH_C0 = 0.28209479177387814\n",
        "        r = np.clip(0.5 + SH_C0 * f_dc_0, 0.0, 1.0)\n",
        "        g = np.clip(0.5 + SH_C0 * f_dc_1, 0.0, 1.0)\n",
        "        b = np.clip(0.5 + SH_C0 * f_dc_2, 0.0, 1.0)\n",
        "    else:\n",
        "        r = g = b = np.ones_like(x) * 0.8\n",
        "\n",
        "    total_points = len(x)\n",
        "    if total_points > max_points:\n",
        "        idx = np.random.choice(total_points, max_points, replace=False)\n",
        "        x, y, z = x[idx], y[idx], z[idx]\n",
        "        r, g, b = r[idx], g[idx], b[idx]\n",
        "\n",
        "    # Chuẩn hóa màu hex RGB\n",
        "    colors_hex = [f'rgb({int(ri*255)},{int(gi*255)},{int(bi*255)})' for ri, gi, bi in zip(r, g, b)]\n",
        "\n",
        "    # Ép CSS Full-Width 100% tràn toàn bộ chiều ngang VS Code Notebook Output Cell\n",
        "    display(HTML(\"\"\"\n",
        "    <style>\n",
        "    .cell-output-ipywidget-background, .output_subarea, .js-plotly-plot, .plotly, .plot-container {\n",
        "        width: 100% !important;\n",
        "        max-width: 100% !important;\n",
        "    }\n",
        "    .js-plotly-plot .plotly .main-svg {\n",
        "        background: transparent !important;\n",
        "    }\n",
        "    </style>\n",
        "    \"\"\"))\n",
        "\n",
        "    # Biểu diễn Mây Điểm 3D\n",
        "    scatter = go.Scatter3d(\n",
        "        x=x, y=y, z=z,\n",
        "        mode='markers',\n",
        "        marker=dict(\n",
        "            size=2.2,\n",
        "            color=colors_hex,\n",
        "            opacity=0.92\n",
        "        ),\n",
        "        name='Mây Điểm 3D',\n",
        "        hoverinfo='none'\n",
        "    )\n",
        "\n",
        "    fig = go.Figure(data=[scatter])\n",
        "\n",
        "    # 60 khung hình quay 360 độ quanh tâm mây điểm (Turntable Rotation)\n",
        "    frames = []\n",
        "    n_frames = 60\n",
        "    r_cam = 2.2\n",
        "    for i in range(n_frames):\n",
        "        theta = 2 * np.pi * i / n_frames\n",
        "        cam_x = r_cam * np.cos(theta)\n",
        "        cam_y = r_cam * np.sin(theta)\n",
        "        frames.append(go.Frame(\n",
        "            layout=dict(\n",
        "                scene_camera=dict(\n",
        "                    eye=dict(x=cam_x, y=cam_y, z=0.8),\n",
        "                    center=dict(x=0, y=0, z=0),\n",
        "                    up=dict(x=0, y=0, z=1)\n",
        "                )\n",
        "            ),\n",
        "            name=f\"frame_{i}\"\n",
        "        ))\n",
        "    fig.frames = frames\n",
        "\n",
        "    # Cấu hình giao diện Full-Width Nền Đen Tuyền (#000000)\n",
        "    fig.update_layout(\n",
        "        autosize=True,\n",
        "        height=750,\n",
        "        title=dict(\n",
        "            text=f\"🌐 <b>Khâu 1: Mây Điểm Ban Đầu (Iter 0)</b> | Số điểm: <b>{total_points:,}</b>\",\n",
        "            x=0.01, y=0.98,\n",
        "            font=dict(size=16, color='#38bdf8')\n",
        "        ),\n",
        "        scene=dict(\n",
        "            xaxis=dict(visible=False),\n",
        "            yaxis=dict(visible=False),\n",
        "            zaxis=dict(visible=False),\n",
        "            aspectmode='data',\n",
        "            bgcolor='#000000'\n",
        "        ),\n",
        "        paper_bgcolor='#000000',\n",
        "        plot_bgcolor='#000000',\n",
        "        font=dict(color='#ffffff', family='system-ui'),\n",
        "        margin=dict(l=0, r=0, b=0, t=40),\n",
        "        updatemenus=[\n",
        "            dict(\n",
        "                type=\"buttons\",\n",
        "                showactive=True,\n",
        "                y=0.96, x=0.01,\n",
        "                xanchor=\"left\", yanchor=\"top\",\n",
        "                pad=dict(t=0, r=10),\n",
        "                bgcolor='rgba(30, 41, 59, 0.9)',\n",
        "                bordercolor='rgba(255, 255, 255, 0.3)',\n",
        "                font=dict(color='#ffffff', size=13),\n",
        "                buttons=[\n",
        "                    dict(\n",
        "                        label=\"▶ Tự Động Quay 360°\",\n",
        "                        method=\"animate\",\n",
        "                        args=[None, dict(\n",
        "                            frame=dict(duration=50, redraw=False),\n",
        "                            fromcurrent=True,\n",
        "                            mode=\"immediate\",\n",
        "                            loop=True\n",
        "                        )]\n",
        "                    ),\n",
        "                    dict(\n",
        "                        label=\"⏸ Tạm Dừng (Tự Xoay Chuột 360°)\",\n",
        "                        method=\"animate\",\n",
        "                        args=[[None], dict(\n",
        "                            frame=dict(duration=0, redraw=False),\n",
        "                            mode=\"immediate\",\n",
        "                            transition=dict(duration=0)\n",
        "                        )]\n",
        "                    )\n",
        "                ]\n",
        "            )\n",
        "        ]\n",
        "    )\n",
        "\n",
        "    print(\"✨ Đã dựng thành công Khung Mây Điểm 3D Full-Width Nền Đen Tuyền (#000000)!\")\n",
        "    fig.show(config={'responsive': True, 'displayModeBar': True})\n",
        "\n",
        "# ── Đọc và Hiển Thị File Mây Điểm Local ─────────────────────────────────────────\n",
        "local_base = os.path.join(os.getcwd(), \"counter_demo_video\")\n",
        "ply_path = os.path.join(local_base, \"step1_initial_points\", \"initial_point_cloud.ply\")\n",
        "\n",
        "if not os.path.exists(ply_path):\n",
        "    ply_path = r\"C:\\Users\\YUT9HC\\Desktop\\Z\\thesis-all\\counter_demo_video\\step1_initial_points\\initial_point_cloud.ply\"\n",
        "\n",
        "if os.path.exists(ply_path):\n",
        "    display_interactive_point_cloud_plotly(ply_path)\n",
        "else:\n",
        "    print(f\"⚠️ Không tìm thấy file tại {ply_path}. Vui lòng kiểm tra lại thư mục counter_demo_video!\")"
    ]
})

# Cell 3: 5 Rows x 2 Columns Grid for Ground Truth vs Step 1 Point Cloud Renders
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_03_gt_vs_step1_renders_grid",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── KHÂU 1 (BỔ SUNG): BẢNG SO SÁNH 10 SCENE GIỮA GROUND TRUTH & MÂY ĐIỂM KHÂU 1 ────\n",
        "import os\n",
        "import glob\n",
        "from PIL import Image\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "def display_gt_vs_initial_point_cloud_grid(gt_dir=None, step1_dir=None):\n",
        "    \"\"\"\n",
        "    Hiển thị Khung Lưới (5 Dòng x 2 Cột) So Sánh 10 Cảnh Scene giữa:\n",
        "    - Cột Trái: Ảnh chụp thực tế Ground Truth (DSCFxxxx.png/JPG)\n",
        "    - Cột Phải: Ảnh kết xuất mây điểm ban đầu tương ứng (view_xx_DSCFxxxx.png)\n",
        "    \"\"\"\n",
        "    camera_names = [\"DSCF5857\", \"DSCF5881\", \"DSCF5905\", \"DSCF5929\", \"DSCF5953\", \n",
        "                    \"DSCF5985\", \"DSCF6009\", \"DSCF6033\", \"DSCF6057\", \"DSCF6089\"]\n",
        "\n",
        "    # 1. Tìm vị trí thư mục step1_initial_points\n",
        "    if not step1_dir or not os.path.exists(step1_dir):\n",
        "        possible_step1 = [\n",
        "            os.path.join(os.getcwd(), \"counter_demo_video\", \"step1_initial_points\"),\n",
        "            r\"C:\\Users\\YUT9HC\\Desktop\\Z\\thesis-all\\counter_demo_video\\step1_initial_points\",\n",
        "            \"/kaggle/working/demo_video_counter/step1_initial_points\",\n",
        "            \"/content/drive/MyDrive/demo_video_counter/counter_demo_video/step1_initial_points\"\n",
        "        ]\n",
        "        for p in possible_step1:\n",
        "            if os.path.exists(p):\n",
        "                step1_dir = p\n",
        "                break\n",
        "\n",
        "    # 2. Tự động quét tìm vị trí tập ảnh Ground Truth\n",
        "    if not gt_dir or not os.path.exists(gt_dir):\n",
        "        possible_gt_dirs = [\n",
        "            r\"C:\\Users\\YUT9HC\\Desktop\\Z\\thesis-all\\spec-fastgs\\datasets\\mipnerf360\\counter\\images_8\",\n",
        "            r\"C:\\Users\\YUT9HC\\Desktop\\Z\\thesis-all\\spec-fastgs\\datasets\\mipnerf360\\counter\\images\",\n",
        "            \"counter/images_8\",\n",
        "            \"images_8\",\n",
        "            \"/kaggle/working/thesis-all/spec-fastgs/datasets/mipnerf360/counter/images_8\",\n",
        "            \"/content/drive/MyDrive/demo_video_counter/counter/images_8\"\n",
        "        ]\n",
        "        for candidate in possible_gt_dirs:\n",
        "            if os.path.exists(candidate):\n",
        "                gt_dir = candidate\n",
        "                break\n",
        "\n",
        "    if not gt_dir or not os.path.exists(gt_dir):\n",
        "        for search_root in [os.getcwd(), r\"C:\\Users\\YUT9HC\\Desktop\\Z\\thesis-all\", \"/kaggle/working\", \"/content/drive/MyDrive\", \".\"]:\n",
        "            if os.path.exists(search_root):\n",
        "                for root, dirs, files in os.walk(search_root):\n",
        "                    for f in files:\n",
        "                        if f.startswith(\"DSCF5857\") and not f.startswith(\"view_\"):\n",
        "                            gt_dir = root\n",
        "                            break\n",
        "                    if gt_dir:\n",
        "                        break\n",
        "            if gt_dir:\n",
        "                break\n",
        "\n",
        "    print(f\"📂 Thư mục mây điểm Khâu 1: {step1_dir}\")\n",
        "    print(f\"📷 Thư mục Ground Truth: {gt_dir if gt_dir else '⚠️ Chưa phát hiện tập ảnh GT'}\")\n",
        "\n",
        "    # Vẽ bảng 5 dòng x 2 cột = 10 ô so sánh scene\n",
        "    fig, axes = plt.subplots(5, 2, figsize=(20, 25), facecolor='#000000')\n",
        "    fig.suptitle(\"📸 SO SÁNH 10 CẢNH SCENE: GROUND TRUTH VS MÂY ĐIỂM BAN ĐẦU (KHÂU 1)\", \n",
        "                 fontsize=20, color='#38bdf8', fontweight='bold', y=0.995)\n",
        "\n",
        "    for idx, cam_name in enumerate(camera_names):\n",
        "        row = idx // 2\n",
        "        col = idx % 2\n",
        "        ax = axes[row, col]\n",
        "        ax.set_facecolor('#000000')\n",
        "\n",
        "        # 1. Tìm ảnh GT\n",
        "        gt_path = None\n",
        "        if gt_dir and os.path.exists(gt_dir):\n",
        "            for ext in [\".JPG\", \".jpg\", \".png\", \".PNG\", \".jpeg\"]:\n",
        "                p = os.path.join(gt_dir, cam_name + ext)\n",
        "                if os.path.exists(p):\n",
        "                    gt_path = p\n",
        "                    break\n",
        "\n",
        "        # 2. Tìm ảnh Khâu 1 render\n",
        "        step1_path = None\n",
        "        if step1_dir and os.path.exists(step1_dir):\n",
        "            pattern = os.path.join(step1_dir, f\"view_*_{cam_name}.png\")\n",
        "            matches = glob.glob(pattern)\n",
        "            if matches:\n",
        "                step1_path = matches[0]\n",
        "\n",
        "        if gt_path and os.path.exists(gt_path) and step1_path and os.path.exists(step1_path):\n",
        "            img_gt = Image.open(gt_path).convert('RGB')\n",
        "            img_step1 = Image.open(step1_path).convert('RGB')\n",
        "\n",
        "            # Resize GT để khớp chiều cao với ảnh render Khâu 1\n",
        "            h = img_step1.height\n",
        "            w_gt = int(img_gt.width * (h / img_gt.height))\n",
        "            img_gt_resized = img_gt.resize((w_gt, h), Image.Resampling.LANCZOS)\n",
        "\n",
        "            # Ghép đôi: Ảnh GT bên Trái | Ảnh Render Khâu 1 bên Phải\n",
        "            combined = Image.new('RGB', (img_gt_resized.width + img_step1.width, h))\n",
        "            combined.paste(img_gt_resized, (0, 0))\n",
        "            combined.paste(img_step1, (img_gt_resized.width, 0))\n",
        "\n",
        "            ax.imshow(combined)\n",
        "            ax.set_title(f\"Scene {idx+1:02d}: {cam_name}  |  TRÁI: Ground Truth  ⇄  PHẢI: Mây Điểm Khâu 1\", \n",
        "                         color='#ffffff', fontsize=12, fontweight='bold', pad=8)\n",
        "        elif step1_path and os.path.exists(step1_path):\n",
        "            img_step1 = Image.open(step1_path).convert('RGB')\n",
        "            ax.imshow(img_step1)\n",
        "            ax.set_title(f\"Scene {idx+1:02d}: {cam_name}  (Mây Điểm Khâu 1)\", color='#fbbf24', fontsize=12)\n",
        "        else:\n",
        "            ax.text(0.5, 0.5, f\"Scene {idx+1:02d}: {cam_name}\\n[Không tìm thấy tệp ảnh]\", color='#ef4444', ha='center', va='center', fontsize=14)\n",
        "\n",
        "        ax.axis('off')\n",
        "\n",
        "    plt.tight_layout(rect=[0, 0, 1, 0.99])\n",
        "    plt.show()\n",
        "\n",
        "# ── Thực thi hiển thị lưới 5 dòng x 2 cột ────────────────────────────────────────\n",
        "display_gt_vs_initial_point_cloud_grid()"
    ]
})

notebook_json = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.10.12"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(notebook_json, f, indent=2, ensure_ascii=False)

shutil.copy2(notebook_path, fix_notebook_path)

print(f"5x2 Ground Truth Grid Notebook written to:\n- {notebook_path}\n- {fix_notebook_path}")
