import os
import json
import shutil

notebook_path = os.path.abspath(os.path.join("notebooks", "point_cloud_interactive_viewer.ipynb"))
fix_notebook_path = os.path.abspath(os.path.join("fix", "point_cloud_interactive_viewer.ipynb"))
os.makedirs(os.path.dirname(notebook_path), exist_ok=True)
os.makedirs(os.path.dirname(fix_notebook_path), exist_ok=True)

cells = []

# Cell 1: Install Dependencies
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_01_install_deps",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── Cài Đặt Thư Viện Đọc PLY & Thư Viện Biểu Diễn 3D Trực Quan Plotly ─────────\n",
        "!pip install -q plyfile plotly numpy pandas"
    ]
})

# Cell 2: True Full-Width Pure Black 3D Interactive Point Cloud Visualizer (Fixed)
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_02_plotly_interactive_pcd",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── KHÂU 1: Hiển Thị Mây Điểm Ban Đầu (Iter 0) True Full-Width Nền Đen 3D ───────────\n",
        "import os\n",
        "import numpy as np\n",
        "from plyfile import PlyData\n",
        "import plotly.graph_objects as go\n",
        "from IPython.display import HTML, display\n",
        "\n",
        "def display_interactive_point_cloud_plotly(ply_path, max_points=50000):\n",
        "    \"\"\"\n",
        "    Hiển thị Khung Mây Điểm 3D Tương Tác Full-Width Nền Đen Tuyền (#000000).\n",
        "    - Tự động Ép Khung Width 100% tràn ngập toàn bộ ô Notebook trong VS Code.\n",
        "    - Nền Đen Tuyền (#000000) làm nổi bật toàn bộ các điểm mây 3D sắc nét.\n",
        "    - Nút '▶ Tự Động Quay 360°' và '⏸ Tạm Dừng' xoay mây điểm quanh tâm.\n",
        "    \"\"\"\n",
        "    if not os.path.exists(ply_path):\n",
        "        print(f\"❌ Không tìm thấy file point cloud tại: {ply_path}\")\n",
        "        return\n",
        "\n",
        "    print(f\"📂 Đang nạp Mây Điểm 3D Khâu 1: {ply_path} ...\")\n",
        "    plydata = PlyData.read(ply_path)\n",
        "    vertex = plydata['vertex']\n",
        "\n",
        "    x = np.asarray(vertex['x'], dtype=np.float32)\n",
        "    y = np.asarray(vertex['y'], dtype=np.float32)\n",
        "    z = np.asarray(vertex['z'], dtype=np.float32)\n",
        "\n",
        "    # Giải mã màu sắc từ thuộc tính PLY (Hỗ trợ cả PLY thường & 3DGS Spherical Harmonics)\n",
        "    names = [p.name for p in vertex.properties]\n",
        "    if 'red' in names and 'green' in names and 'blue' in names:\n",
        "        r = np.asarray(vertex['red'], dtype=np.float32)\n",
        "        g = np.asarray(vertex['green'], dtype=np.float32)\n",
        "        b = np.asarray(vertex['blue'], dtype=np.float32)\n",
        "        if r.max() > 1.0:\n",
        "            r, g, b = r / 255.0, g / 255.0, b / 255.0\n",
        "    elif 'f_dc_0' in names and 'f_dc_1' in names and 'f_dc_2' in names:\n",
        "        f_dc_0 = np.asarray(vertex['f_dc_0'], dtype=np.float32)\n",
        "        f_dc_1 = np.asarray(vertex['f_dc_1'], dtype=np.float32)\n",
        "        f_dc_2 = np.asarray(vertex['f_dc_2'], dtype=np.float32)\n",
        "        SH_C0 = 0.28209479177387814\n",
        "        r = np.clip(0.5 + SH_C0 * f_dc_0, 0.0, 1.0)\n",
        "        g = np.clip(0.5 + SH_C0 * f_dc_1, 0.0, 1.0)\n",
        "        b = np.clip(0.5 + SH_C0 * f_dc_2, 0.0, 1.0)\n",
        "    else:\n",
        "        r = g = b = np.ones_like(x) * 0.8\n",
        "\n",
        "    total_points = len(x)\n",
        "    if total_points > max_points:\n",
        "        idx = np.random.choice(total_points, max_points, replace=False)\n",
        "        x, y, z = x[idx], y[idx], z[idx]\n",
        "        r, g, b = r[idx], g[idx], b[idx]\n",
        "\n",
        "    # Chuẩn hóa màu hex RGB\n",
        "    colors_hex = [f'rgb({int(ri*255)},{int(gi*255)},{int(bi*255)})' for ri, gi, bi in zip(r, g, b)]\n",
        "\n",
        "    # Ép CSS Full-Width 100% tràn toàn bộ chiều ngang VS Code Notebook Output Cell\n",
        "    display(HTML(\"\"\"\n",
        "    <style>\n",
        "    .cell-output-ipywidget-background, .output_subarea, .js-plotly-plot, .plotly, .plot-container {\n",
        "        width: 100% !important;\n",
        "        max-width: 100% !important;\n",
        "    }\n",
        "    .js-plotly-plot .plotly .main-svg {\n",
        "        background: transparent !important;\n",
        "    }\n",
        "    </style>\n",
        "    \"\"\"))\n",
        "\n",
        "    # Biểu diễn Mây Điểm 3D\n",
        "    scatter = go.Scatter3d(\n",
        "        x=x, y=y, z=z,\n",
        "        mode='markers',\n",
        "        marker=dict(\n",
        "            size=2.2,\n",
        "            color=colors_hex,\n",
        "            opacity=0.92\n",
        "        ),\n",
        "        name='Mây Điểm 3D',\n",
        "        hoverinfo='none'\n",
        "    )\n",
        "\n",
        "    fig = go.Figure(data=[scatter])\n",
        "\n",
        "    # 60 khung hình quay 360 độ quanh tâm mây điểm (Turntable Rotation)\n",
        "    frames = []\n",
        "    n_frames = 60\n",
        "    r_cam = 2.2\n",
        "    for i in range(n_frames):\n",
        "        theta = 2 * np.pi * i / n_frames\n",
        "        cam_x = r_cam * np.cos(theta)\n",
        "        cam_y = r_cam * np.sin(theta)\n",
        "        frames.append(go.Frame(\n",
        "            layout=dict(\n",
        "                scene_camera=dict(\n",
        "                    eye=dict(x=cam_x, y=cam_y, z=0.8),\n",
        "                    center=dict(x=0, y=0, z=0),\n",
        "                    up=dict(x=0, y=0, z=1)\n",
        "                )\n",
        "            ),\n",
        "            name=f\"frame_{i}\"\n",
        "        ))\n",
        "    fig.frames = frames\n",
        "\n",
        "    # Cấu hình giao diện Full-Width Nền Đen Tuyền (#000000)\n",
        "    fig.update_layout(\n",
        "        autosize=True,\n",
        "        height=750,\n",
        "        title=dict(\n",
        "            text=f\"🌐 <b>Khâu 1: Mây Điểm Ban Đầu (Iter 0)</b> | Số điểm: <b>{total_points:,}</b>\",\n",
        "            x=0.01, y=0.98,\n",
        "            font=dict(size=16, color='#38bdf8')\n",
        "        ),\n",
        "        scene=dict(\n",
        "            xaxis=dict(visible=False),\n",
        "            yaxis=dict(visible=False),\n",
        "            zaxis=dict(visible=False),\n",
        "            aspectmode='data',\n",
        "            bgcolor='#000000'\n",
        "        ),\n",
        "        paper_bgcolor='#000000',\n",
        "        plot_bgcolor='#000000',\n",
        "        font=dict(color='#ffffff', family='system-ui'),\n",
        "        margin=dict(l=0, r=0, b=0, t=40),\n",
        "        updatemenus=[\n",
        "            dict(\n",
        "                type=\"buttons\",\n",
        "                showactive=True,\n",
        "                y=0.96, x=0.01,\n",
        "                xanchor=\"left\", yanchor=\"top\",\n",
        "                pad=dict(t=0, r=10),\n",
        "                bgcolor='rgba(30, 41, 59, 0.9)',\n",
        "                bordercolor='rgba(255, 255, 255, 0.3)',\n",
        "                font=dict(color='#ffffff', size=13),\n",
        "                buttons=[\n",
        "                    dict(\n",
        "                        label=\"▶ Tự Động Quay 360°\",\n",
        "                        method=\"animate\",\n",
        "                        args=[None, dict(\n",
        "                            frame=dict(duration=50, redraw=False),\n",
        "                            fromcurrent=True,\n",
        "                            mode=\"immediate\",\n",
        "                            loop=True\n",
        "                        )]\n",
        "                    ),\n",
        "                    dict(\n",
        "                        label=\"⏸ Tạm Dừng (Tự Xoay Chuột 360°)\",\n",
        "                        method=\"animate\",\n",
        "                        args=[[None], dict(\n",
        "                            frame=dict(duration=0, redraw=False),\n",
        "                            mode=\"immediate\",\n",
        "                            transition=dict(duration=0)\n",
        "                        )]\n",
        "                    )\n",
        "                ]\n",
        "            )\n",
        "        ]\n",
        "    )\n",
        "\n",
        "    print(\"✨ Đã dựng thành công Khung Mây Điểm 3D Full-Width Nền Đen Tuyền (#000000)!\")\n",
        "    fig.show(config={'responsive': True, 'displayModeBar': True})\n",
        "\n",
        "# ── Đọc và Hiển Thị File Mây Điểm Local ─────────────────────────────────────────\n",
        "local_base = os.path.join(os.getcwd(), \"counter_demo_video\")\n",
        "ply_path = os.path.join(local_base, \"step1_initial_points\", \"initial_point_cloud.ply\")\n",
        "\n",
        "if not os.path.exists(ply_path):\n",
        "    ply_path = r\"C:\\Users\\YUT9HC\\Desktop\\Z\\thesis-all\\counter_demo_video\\step1_initial_points\\initial_point_cloud.ply\"\n",
        "\n",
        "if os.path.exists(ply_path):\n",
        "    display_interactive_point_cloud_plotly(ply_path)\n",
        "else:\n",
        "    print(f\"⚠️ Không tìm thấy file tại {ply_path}. Vui lòng kiểm tra lại thư mục counter_demo_video!\")"
    ]
})

notebook_json = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.10.12"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(notebook_json, f, indent=2, ensure_ascii=False)

shutil.copy2(notebook_path, fix_notebook_path)

print(f"Fixed Pure Black Full-Width Plotly 3D Notebook written to:\n- {notebook_path}\n- {fix_notebook_path}")
