import os
import json
import shutil

notebook_path = os.path.abspath(os.path.join("notebooks", "point_cloud_interactive_viewer.ipynb"))
fix_notebook_path = os.path.abspath(os.path.join("fix", "point_cloud_interactive_viewer.ipynb"))
os.makedirs(os.path.dirname(notebook_path), exist_ok=True)
os.makedirs(os.path.dirname(fix_notebook_path), exist_ok=True)

cells = []

# Cell 1: Install Dependencies
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_01_install_deps",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── Cài Đặt Thư Viện Đọc PLY, Xử Lý Ảnh & Biểu Diễn 3D Trực Quan ───────────────\n",
        "!pip install -q plyfile plotly numpy pandas matplotlib pillow"
    ]
})

# Cell 2: True Full-Width Pure Black 3D Interactive Point Cloud Visualizer (Khâu 1)
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_02_plotly_interactive_pcd",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── KHÂU 1: Hiển Thị Mây Điểm Ban Đầu (Iter 0) True Full-Width Nền Đen 3D ───────────\n",
        "import os\n",
        "import numpy as np\n",
        "from plyfile import PlyData\n",
        "import plotly.graph_objects as go\n",
        "from IPython.display import HTML, display\n",
        "\n",
        "def display_interactive_point_cloud_plotly(ply_path, max_points=50000):\n",
        "    \"\"\"\n",
        "    Hiển thị Khung Mây Điểm 3D Tương Tác Full-Width Nền Đen Tuyền (#000000).\n",
        "    - Tự động Ép Khung Width 100% tràn ngập toàn bộ ô Notebook trong VS Code.\n",
        "    - Nền Đen Tuyền (#000000) làm nổi bật toàn bộ các điểm mây 3D sắc nét.\n",
        "    - Nút '▶ Tự Động Quay 360°' và '⏸ Tạm Dừng' xoay mây điểm quanh tâm.\n",
        "    \"\"\"\n",
        "    if not os.path.exists(ply_path):\n",
        "        print(f\"❌ Không tìm thấy file point cloud tại: {ply_path}\")\n",
        "        return\n",
        "\n",
        "    print(f\"📂 Đang nạp Mây Điểm 3D Khâu 1: {ply_path} ...\")\n",
        "    plydata = PlyData.read(ply_path)\n",
        "    vertex = plydata['vertex']\n",
        "\n",
        "    x = np.asarray(vertex['x'], dtype=np.float32)\n",
        "    y = np.asarray(vertex['y'], dtype=np.float32)\n",
        "    z = np.asarray(vertex['z'], dtype=np.float32)\n",
        "\n",
        "    names = [p.name for p in vertex.properties]\n",
        "    if 'red' in names and 'green' in names and 'blue' in names:\n",
        "        r = np.asarray(vertex['red'], dtype=np.float32)\n",
        "        g = np.asarray(vertex['green'], dtype=np.float32)\n",
        "        b = np.asarray(vertex['blue'], dtype=np.float32)\n",
        "        if r.max() > 1.0:\n",
        "            r, g, b = r / 255.0, g / 255.0, b / 255.0\n",
        "    elif 'f_dc_0' in names and 'f_dc_1' in names and 'f_dc_2' in names:\n",
        "        f_dc_0 = np.asarray(vertex['f_dc_0'], dtype=np.float32)\n",
        "        f_dc_1 = np.asarray(vertex['f_dc_1'], dtype=np.float32)\n",
        "        f_dc_2 = np.asarray(vertex['f_dc_2'], dtype=np.float32)\n",
        "        SH_C0 = 0.28209479177387814\n",
        "        r = np.clip(0.5 + SH_C0 * f_dc_0, 0.0, 1.0)\n",
        "        g = np.clip(0.5 + SH_C0 * f_dc_1, 0.0, 1.0)\n",
        "        b = np.clip(0.5 + SH_C0 * f_dc_2, 0.0, 1.0)\n",
        "    else:\n",
        "        r = g = b = np.ones_like(x) * 0.8\n",
        "\n",
        "    total_points = len(x)\n",
        "    if total_points > max_points:\n",
        "        idx = np.random.choice(total_points, max_points, replace=False)\n",
        "        x, y, z = x[idx], y[idx], z[idx]\n",
        "        r, g, b = r[idx], g[idx], b[idx]\n",
        "\n",
        "    colors_hex = [f'rgb({int(ri*255)},{int(gi*255)},{int(bi*255)})' for ri, gi, bi in zip(r, g, b)]\n",
        "\n",
        "    display(HTML(\"\"\"\n",
        "    <style>\n",
        "    .cell-output-ipywidget-background, .output_subarea, .js-plotly-plot, .plotly, .plot-container {\n",
        "        width: 100% !important;\n",
        "        max-width: 100% !important;\n",
        "    }\n",
        "    .js-plotly-plot .plotly .main-svg {\n",
        "        background: transparent !important;\n",
        "    }\n",
        "    </style>\n",
        "    \"\"\"))\n",
        "\n",
        "    scatter = go.Scatter3d(\n",
        "        x=x, y=y, z=z,\n",
        "        mode='markers',\n",
        "        marker=dict(size=2.2, color=colors_hex, opacity=0.92),\n",
        "        name='Mây Điểm 3D',\n",
        "        hoverinfo='none'\n",
        "    )\n",
        "\n",
        "    fig = go.Figure(data=[scatter])\n",
        "\n",
        "    frames = []\n",
        "    n_frames = 60\n",
        "    r_cam = 2.2\n",
        "    for i in range(n_frames):\n",
        "        theta = 2 * np.pi * i / n_frames\n",
        "        cam_x = r_cam * np.cos(theta)\n",
        "        cam_y = r_cam * np.sin(theta)\n",
        "        frames.append(go.Frame(\n",
        "            layout=dict(\n",
        "                scene_camera=dict(\n",
        "                    eye=dict(x=cam_x, y=cam_y, z=0.8),\n",
        "                    center=dict(x=0, y=0, z=0),\n",
        "                    up=dict(x=0, y=0, z=1)\n",
        "                )\n",
        "            ),\n",
        "            name=f\"frame_{i}\"\n",
        "        ))\n",
        "    fig.frames = frames\n",
        "\n",
        "    fig.update_layout(\n",
        "        autosize=True,\n",
        "        height=750,\n",
        "        showlegend=False,\n",
        "        title=dict(\n",
        "            text=f\"🌐 <b>Khâu 1: Mây Điểm Ban Đầu (Iter 0)</b> | Số điểm: <b>{total_points:,}</b>\",\n",
        "            x=0.01, y=0.98,\n",
        "            font=dict(size=16, color='#38bdf8')\n",
        "        ),\n",
        "        scene=dict(\n",
        "            xaxis=dict(visible=False),\n",
        "            yaxis=dict(visible=False),\n",
        "            zaxis=dict(visible=False),\n",
        "            aspectmode='data',\n",
        "            bgcolor='#000000'\n",
        "        ),\n",
        "        paper_bgcolor='#000000',\n",
        "        plot_bgcolor='#000000',\n",
        "        font=dict(color='#ffffff', family='system-ui'),\n",
        "        margin=dict(l=0, r=0, b=0, t=40),\n",
        "        updatemenus=[\n",
        "            dict(\n",
        "                type=\"buttons\",\n",
        "                showactive=True,\n",
        "                y=0.96, x=0.01,\n",
        "                xanchor=\"left\", yanchor=\"top\",\n",
        "                pad=dict(t=0, r=10),\n",
        "                bgcolor='rgba(30, 41, 59, 0.9)',\n",
        "                bordercolor='rgba(255, 255, 255, 0.3)',\n",
        "                font=dict(color='#ffffff', size=13),\n",
        "                buttons=[\n",
        "                    dict(\n",
        "                        label=\"▶ Tự Động Quay 360°\",\n",
        "                        method=\"animate\",\n",
        "                        args=[None, dict(frame=dict(duration=50, redraw=False), fromcurrent=True, mode=\"immediate\", loop=True)]\n",
        "                    ),\n",
        "                    dict(\n",
        "                        label=\"⏸ Tạm Dừng (Tự Xoay Chuột 360°)\",\n",
        "                        method=\"animate\",\n",
        "                        args=[[None], dict(frame=dict(duration=0, redraw=False), mode=\"immediate\", transition=dict(duration=0))]\n",
        "                    )\n",
        "                ]\n",
        "            )\n",
        "        ]\n",
        "    )\n",
        "\n",
        "    print(\"✨ Đã dựng thành công Khung Mây Điểm 3D Full-Width Nền Đen Tuyền (#000000)!\")\n",
        "    fig.show(config={'responsive': True, 'displayModeBar': True})\n",
        "\n",
        "local_base = os.path.join(os.getcwd(), \"counter_demo_video\")\n",
        "ply_path = os.path.join(local_base, \"step1_initial_points\", \"initial_point_cloud.ply\")\n",
        "if not os.path.exists(ply_path):\n",
        "    ply_path = r\"C:\\Users\\YUT9HC\\Desktop\\Z\\thesis-all\\counter_demo_video\\step1_initial_points\\initial_point_cloud.ply\"\n",
        "\n",
        "if os.path.exists(ply_path):\n",
        "    display_interactive_point_cloud_plotly(ply_path)\n",
        "else:\n",
        "    print(f\"⚠️ Không tìm thấy file tại {ply_path}. Vui lòng kiểm tra lại thư mục counter_demo_video!\")"
    ]
})

# Cell 3: 5 Rows x 2 Columns Grid for Ground Truth vs Step 1 Point Cloud Renders
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_03_gt_vs_step1_renders_grid",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── KHÂU 1 (BỔ SUNG): BẢNG SO SÁNH 10 SCENE GIỮA GROUND TRUTH & MÂY ĐIỂM KHÂU 1 ────\n",
        "import os\n",
        "import glob\n",
        "from PIL import Image\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "def display_gt_vs_initial_point_cloud_grid(gt_dir=None, step1_dir=None):\n",
        "    \"\"\"\n",
        "    Hiển thị Khung Lưới (5 Dòng x 2 Cột) So Sánh 10 Cảnh Scene giữa:\n",
        "    - Cột Trái: Ảnh chụp thực tế Ground Truth (DSCFxxxx.png/JPG)\n",
        "    - Cột Phải: Ảnh kết xuất mây điểm ban đầu tương ứng (view_xx_DSCFxxxx.png)\n",
        "    \"\"\"\n",
        "    camera_names = [\"DSCF5857\", \"DSCF5881\", \"DSCF5905\", \"DSCF5929\", \"DSCF5953\", \n",
        "                    \"DSCF5985\", \"DSCF6009\", \"DSCF6033\", \"DSCF6057\", \"DSCF6089\"]\n",
        "\n",
        "    if not step1_dir or not os.path.exists(step1_dir):\n",
        "        possible_step1 = [\n",
        "            os.path.join(os.getcwd(), \"counter_demo_video\", \"step1_initial_points\"),\n",
        "            r\"C:\\Users\\YUT9HC\\Desktop\\Z\\thesis-all\\counter_demo_video\\step1_initial_points\",\n",
        "            \"/kaggle/working/demo_video_counter/step1_initial_points\",\n",
        "            \"/content/drive/MyDrive/demo_video_counter/counter_demo_video/step1_initial_points\"\n",
        "        ]\n",
        "        for p in possible_step1:\n",
        "            if os.path.exists(p):\n",
        "                step1_dir = p\n",
        "                break\n",
        "\n",
        "    if not gt_dir or not os.path.exists(gt_dir):\n",
        "        possible_gt_dirs = [\n",
        "            r\"C:\\Users\\YUT9HC\\Desktop\\Z\\thesis-all\\spec-fastgs\\datasets\\mipnerf360\\counter\\images_8\",\n",
        "            r\"C:\\Users\\YUT9HC\\Desktop\\Z\\thesis-all\\spec-fastgs\\datasets\\mipnerf360\\counter\\images\",\n",
        "            \"counter/images_8\",\n",
        "            \"images_8\",\n",
        "            \"/kaggle/working/thesis-all/spec-fastgs/datasets/mipnerf360/counter/images_8\",\n",
        "            \"/content/drive/MyDrive/demo_video_counter/counter/images_8\"\n",
        "        ]\n",
        "        for candidate in possible_gt_dirs:\n",
        "            if os.path.exists(candidate):\n",
        "                gt_dir = candidate\n",
        "                break\n",
        "\n",
        "    if not gt_dir or not os.path.exists(gt_dir):\n",
        "        for search_root in [os.getcwd(), r\"C:\\Users\\YUT9HC\\Desktop\\Z\\thesis-all\", \"/kaggle/working\", \"/content/drive/MyDrive\", \".\"]:\n",
        "            if os.path.exists(search_root):\n",
        "                for root, dirs, files in os.walk(search_root):\n",
        "                    for f in files:\n",
        "                        if f.startswith(\"DSCF5857\") and not f.startswith(\"view_\"):\n",
        "                            gt_dir = root\n",
        "                            break\n",
        "                    if gt_dir:\n",
        "                        break\n",
        "            if gt_dir:\n",
        "                break\n",
        "\n",
        "    print(f\"📂 Thư mục mây điểm Khâu 1: {step1_dir}\")\n",
        "    print(f\"📷 Thư mục Ground Truth: {gt_dir if gt_dir else '⚠️ Chưa phát hiện tập ảnh GT'}\")\n",
        "\n",
        "    fig, axes = plt.subplots(5, 2, figsize=(20, 25), facecolor='#000000')\n",
        "    fig.suptitle(\"📸 SO SÁNH 10 CẢNH SCENE: GROUND TRUTH VS MÂY ĐIỂM BAN ĐẦU (KHÂU 1)\", \n",
        "                 fontsize=20, color='#38bdf8', fontweight='bold', y=0.995)\n",
        "\n",
        "    for idx, cam_name in enumerate(camera_names):\n",
        "        row = idx // 2\n",
        "        col = idx % 2\n",
        "        ax = axes[row, col]\n",
        "        ax.set_facecolor('#000000')\n",
        "\n",
        "        gt_path = None\n",
        "        if gt_dir and os.path.exists(gt_dir):\n",
        "            for ext in [\".JPG\", \".jpg\", \".png\", \".PNG\", \".jpeg\"]:\n",
        "                p = os.path.join(gt_dir, cam_name + ext)\n",
        "                if os.path.exists(p):\n",
        "                    gt_path = p\n",
        "                    break\n",
        "\n",
        "        step1_path = None\n",
        "        if step1_dir and os.path.exists(step1_dir):\n",
        "            pattern = os.path.join(step1_dir, f\"view_*_{cam_name}.png\")\n",
        "            matches = glob.glob(pattern)\n",
        "            if matches:\n",
        "                step1_path = matches[0]\n",
        "\n",
        "        if gt_path and os.path.exists(gt_path) and step1_path and os.path.exists(step1_path):\n",
        "            img_gt = Image.open(gt_path).convert('RGB')\n",
        "            img_step1 = Image.open(step1_path).convert('RGB')\n",
        "            h = img_step1.height\n",
        "            w_gt = int(img_gt.width * (h / img_gt.height))\n",
        "            img_gt_resized = img_gt.resize((w_gt, h), Image.Resampling.LANCZOS)\n",
        "            combined = Image.new('RGB', (img_gt_resized.width + img_step1.width, h))\n",
        "            combined.paste(img_gt_resized, (0, 0))\n",
        "            combined.paste(img_step1, (img_gt_resized.width, 0))\n",
        "            ax.imshow(combined)\n",
        "            ax.set_title(f\"Scene {idx+1:02d}: {cam_name}  |  TRÁI: Ground Truth  ⇄  PHẢI: Mây Điểm Khâu 1\", \n",
        "                         color='#ffffff', fontsize=12, fontweight='bold', pad=8)\n",
        "        elif step1_path and os.path.exists(step1_path):\n",
        "            img_step1 = Image.open(step1_path).convert('RGB')\n",
        "            ax.imshow(img_step1)\n",
        "            ax.set_title(f\"Scene {idx+1:02d}: {cam_name}  (Mây Điểm Khâu 1)\", color='#fbbf24', fontsize=12)\n",
        "        else:\n",
        "            ax.text(0.5, 0.5, f\"Scene {idx+1:02d}: {cam_name}\\n[Không tìm thấy tệp ảnh]\", color='#ef4444', ha='center', va='center', fontsize=14)\n",
        "        ax.axis('off')\n",
        "\n",
        "    plt.tight_layout(rect=[0, 0, 1, 0.99])\n",
        "    plt.show()\n",
        "\n",
        "display_gt_vs_initial_point_cloud_grid()"
    ]
})

# Cell 4: 5 Rows x 2 Columns Grid for Ground Truth vs Step 2 Specular Reflection Priors
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_04_gt_vs_step2_priors_grid",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── KHÂU 2: BẢNG SO SÁNH 10 SCENE GIỮA GROUND TRUTH & KHỬ PHẢN XẠ REFLECTION PRIOR ────\n",
        "import os\n",
        "import glob\n",
        "from PIL import Image\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "def display_gt_vs_reflection_priors_grid(gt_dir=None, step2_dir=None):\n",
        "    \"\"\"\n",
        "    Hiển thị Khung Lưới (5 Dòng x 2 Cột) So Sánh 10 Cảnh Scene giữa:\n",
        "    - Cột Trái: Ảnh chụp thực tế Ground Truth (DSCFxxxx.png/JPG)\n",
        "    - Cột Phải: Bản đồ nhiệt phân biệt vùng phản xạ Specular Reflection Prior Khâu 2 (view_xx_DSCFxxxx_prior.png)\n",
        "    \"\"\"\n",
        "    camera_names = [\"DSCF5857\", \"DSCF5881\", \"DSCF5905\", \"DSCF5929\", \"DSCF5953\", \n",
        "                    \"DSCF5985\", \"DSCF6009\", \"DSCF6033\", \"DSCF6057\", \"DSCF6089\"]\n",
        "\n",
        "    if not step2_dir or not os.path.exists(step2_dir):\n",
        "        possible_step2 = [\n",
        "            os.path.join(os.getcwd(), \"counter_demo_video\", \"step2_reflection_priors\"),\n",
        "            r\"C:\\Users\\YUT9HC\\Desktop\\Z\\thesis-all\\counter_demo_video\\step2_reflection_priors\",\n",
        "            \"/kaggle/working/demo_video_counter/step2_reflection_priors\",\n",
        "            \"/content/drive/MyDrive/demo_video_counter/counter_demo_video/step2_reflection_priors\"\n",
        "        ]\n",
        "        for p in possible_step2:\n",
        "            if os.path.exists(p):\n",
        "                step2_dir = p\n",
        "                break\n",
        "\n",
        "    if not gt_dir or not os.path.exists(gt_dir):\n",
        "        possible_gt_dirs = [\n",
        "            r\"C:\\Users\\YUT9HC\\Desktop\\Z\\thesis-all\\spec-fastgs\\datasets\\mipnerf360\\counter\\images_8\",\n",
        "            r\"C:\\Users\\YUT9HC\\Desktop\\Z\\thesis-all\\spec-fastgs\\datasets\\mipnerf360\\counter\\images\",\n",
        "            \"counter/images_8\",\n",
        "            \"images_8\",\n",
        "            \"/kaggle/working/thesis-all/spec-fastgs/datasets/mipnerf360/counter/images_8\",\n",
        "            \"/content/drive/MyDrive/demo_video_counter/counter/images_8\"\n",
        "        ]\n",
        "        for candidate in possible_gt_dirs:\n",
        "            if os.path.exists(candidate):\n",
        "                gt_dir = candidate\n",
        "                break\n",
        "\n",
        "    if not gt_dir or not os.path.exists(gt_dir):\n",
        "        for search_root in [os.getcwd(), r\"C:\\Users\\YUT9HC\\Desktop\\Z\\thesis-all\", \"/kaggle/working\", \"/content/drive/MyDrive\", \".\"]:\n",
        "            if os.path.exists(search_root):\n",
        "                for root, dirs, files in os.walk(search_root):\n",
        "                    for f in files:\n",
        "                        if f.startswith(\"DSCF5857\") and not f.startswith(\"view_\"):\n",
        "                            gt_dir = root\n",
        "                            break\n",
        "                    if gt_dir:\n",
        "                        break\n",
        "            if gt_dir:\n",
        "                break\n",
        "\n",
        "    print(f\"📂 Thư mục Reflection Priors Khâu 2: {step2_dir}\")\n",
        "    print(f\"📷 Thư mục Ground Truth: {gt_dir if gt_dir else '⚠️ Chưa phát hiện tập ảnh GT'}\")\n",
        "\n",
        "    fig, axes = plt.subplots(5, 2, figsize=(20, 25), facecolor='#000000')\n",
        "    fig.suptitle(\"✨ SO SÁNH 10 CẢNH SCENE: GROUND TRUTH VS REFLECTION PRIOR (KHÂU 2)\", \n",
        "                 fontsize=20, color='#38bdf8', fontweight='bold', y=0.995)\n",
        "\n",
        "    for idx, cam_name in enumerate(camera_names):\n",
        "        row = idx // 2\n",
        "        col = idx % 2\n",
        "        ax = axes[row, col]\n",
        "        ax.set_facecolor('#000000')\n",
        "\n",
        "        gt_path = None\n",
        "        if gt_dir and os.path.exists(gt_dir):\n",
        "            for ext in [\".JPG\", \".jpg\", \".png\", \".PNG\", \".jpeg\"]:\n",
        "                p = os.path.join(gt_dir, cam_name + ext)\n",
        "                if os.path.exists(p):\n",
        "                    gt_path = p\n",
        "                    break\n",
        "\n",
        "        step2_path = None\n",
        "        if step2_dir and os.path.exists(step2_dir):\n",
        "            patterns = [\n",
        "                os.path.join(step2_dir, f\"view_*_{cam_name}_prior.png\"),\n",
        "                os.path.join(step2_dir, f\"{cam_name}_ref_score.png\"),\n",
        "                os.path.join(step2_dir, f\"*{cam_name}*.png\")\n",
        "            ]\n",
        "            for pat in patterns:\n",
        "                matches = glob.glob(pat)\n",
        "                if matches:\n",
        "                    step2_path = matches[0]\n",
        "                    break\n",
        "\n",
        "        if gt_path and os.path.exists(gt_path) and step2_path and os.path.exists(step2_path):\n",
        "            img_gt = Image.open(gt_path).convert('RGB')\n",
        "            img_step2 = Image.open(step2_path).convert('RGB')\n",
        "            h = img_step2.height\n",
        "            w_gt = int(img_gt.width * (h / img_gt.height))\n",
        "            img_gt_resized = img_gt.resize((w_gt, h), Image.Resampling.LANCZOS)\n",
        "            combined = Image.new('RGB', (img_gt_resized.width + img_step2.width, h))\n",
        "            combined.paste(img_gt_resized, (0, 0))\n",
        "            combined.paste(img_step2, (img_gt_resized.width, 0))\n",
        "            ax.imshow(combined)\n",
        "            ax.set_title(f\"Scene {idx+1:02d}: {cam_name}  |  TRÁI: Ground Truth  ⇄  PHẢI: Specular Reflection Prior (Khâu 2)\", \n",
        "                         color='#ffffff', fontsize=12, fontweight='bold', pad=8)\n",
        "        elif step2_path and os.path.exists(step2_path):\n",
        "            img_step2 = Image.open(step2_path).convert('RGB')\n",
        "            ax.imshow(img_step2)\n",
        "            ax.set_title(f\"Scene {idx+1:02d}: {cam_name}  (Specular Reflection Prior Khâu 2)\", color='#fbbf24', fontsize=12)\n",
        "        else:\n",
        "            ax.text(0.5, 0.5, f\"Scene {idx+1:02d}: {cam_name}\\n[Không tìm thấy tệp ảnh]\", color='#ef4444', ha='center', va='center', fontsize=14)\n",
        "        ax.axis('off')\n",
        "\n",
        "    plt.tight_layout(rect=[0, 0, 1, 0.99])\n",
        "    plt.show()\n",
        "\n",
        "display_gt_vs_reflection_priors_grid()"
    ]
})

# Cell 5: 3 Rows x 2 Columns Grid for 6 Step 3 Point Clouds (No Legend, Larger Views)
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_05_step3_snapshots_3x2_grid",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── KHÂU 3: BẢNG LƯỚI (3 HÀNG x 2 CỘT) MÂY ĐIỂM 3D GAUSSIAN TỰ DO TƯƠNG TÁC ĐỘC LẬP ──\n",
        "import os\n",
        "import numpy as np\n",
        "from plyfile import PlyData\n",
        "import plotly.graph_objects as go\n",
        "from plotly.subplots import make_subplots\n",
        "from IPython.display import HTML, display\n",
        "\n",
        "def display_step3_snapshots_3x2_grid(step3_dir=None):\n",
        "    \"\"\"\n",
        "    Hiển thị Bảng Canvas To 3 Hàng x 2 Cột Biểu Diễn 6 Tập Mây Điểm 3D Khâu 3:\n",
        "    - Hàng 1 Cột 1: 5,000 Iterations + Số lượng Gaussians\n",
        "    - Hàng 1 Cột 2: 10,000 Iterations + Số lượng Gaussians\n",
        "    - Hàng 2 Cột 1: 15,000 Iterations + Số lượng Gaussians\n",
        "    - Hàng 2 Cột 2: 20,000 Iterations + Số lượng Gaussians\n",
        "    - Hàng 3 Cột 1: 25,000 Iterations + Số lượng Gaussians\n",
        "    - Hàng 3 Cột 2: 30,000 Iterations + Số lượng Gaussians\n",
        "    👉 Không có bảng chú thích bên phải (showlegend=False) để tối ưu không gian hiển thị.\n",
        "    👉 Mỗi ô cell hoàn toàn ĐỘC LẬP (xoay, zoom cell này không ảnh hưởng cell khác).\n",
        "    \"\"\"\n",
        "    iters = [5000, 10000, 15000, 20000, 25000, 30000]\n",
        "\n",
        "    # 1. Tìm vị trí thư mục step3_training_snapshots\n",
        "    if not step3_dir or not os.path.exists(step3_dir):\n",
        "        possible_step3 = [\n",
        "            os.path.join(os.getcwd(), \"counter_demo_video\", \"step3_training_snapshots\"),\n",
        "            r\"C:\\Users\\YUT9HC\\Desktop\\Z\\thesis-all\\counter_demo_video\\step3_training_snapshots\",\n",
        "            \"/kaggle/working/demo_video_counter/step3_training_snapshots\",\n",
        "            \"/content/drive/MyDrive/demo_video_counter/counter_demo_video/step3_training_snapshots\"\n",
        "        ]\n",
        "        for p in possible_step3:\n",
        "            if os.path.exists(p):\n",
        "                step3_dir = p\n",
        "                break\n",
        "\n",
        "    if not step3_dir or not os.path.exists(step3_dir):\n",
        "        print(\"⚠️ Không tìm thấy thư mục step3_training_snapshots. Vui lòng kiểm tra lại đường dẫn!\")\n",
        "        return\n",
        "\n",
        "    print(f\"📂 Đang nạp 6 tệp Mây Điểm 3D Khâu 3 từ: {step3_dir} ...\")\n",
        "\n",
        "    # Ép CSS Full-Width 100% tràn ô VS Code Notebook\n",
        "    display(HTML(\"\"\"\n",
        "    <style>\n",
        "    .cell-output-ipywidget-background, .output_subarea, .js-plotly-plot, .plotly, .plot-container {\n",
        "        width: 100% !important;\n",
        "        max-width: 100% !important;\n",
        "    }\n",
        "    .js-plotly-plot .plotly .main-svg {\n",
        "        background: transparent !important;\n",
        "    }\n",
        "    </style>\n",
        "    \"\"\"))\n",
        "\n",
        "    # Pha 1: Đọc trước tiêu đề và số lượng Gaussians cho 6 tệp PLY (Tránh IndexError)\n",
        "    titles = []\n",
        "    ply_cache = {}\n",
        "    for it in iters:\n",
        "        iter_folder = f\"iter_{it:05d}\"\n",
        "        ply_name = f\"point_cloud_iter_{it:05d}.ply\"\n",
        "        ply_path = os.path.join(step3_dir, iter_folder, ply_name)\n",
        "        if os.path.exists(ply_path):\n",
        "            plydata = PlyData.read(ply_path)\n",
        "            vertex = plydata['vertex']\n",
        "            total_pts = len(vertex)\n",
        "            titles.append(f\"<b>{it:,} Iterations</b><br><span style='color:#60a5fa;'>{total_pts:,} Gaussians</span>\")\n",
        "            ply_cache[it] = (vertex, total_pts)\n",
        "        else:\n",
        "            titles.append(f\"<b>{it:,} Iterations</b><br><span style='color:#ef4444;'>[Chưa tìm thấy .ply]</span>\")\n",
        "\n",
        "    # Pha 2: Khởi tạo 3 hàng x 2 cột 3D scene độc lập với titles chuẩn bị sẵn\n",
        "    fig = make_subplots(\n",
        "        rows=3, cols=2,\n",
        "        specs=[\n",
        "            [{'type': 'scene'}, {'type': 'scene'}],\n",
        "            [{'type': 'scene'}, {'type': 'scene'}],\n",
        "            [{'type': 'scene'}, {'type': 'scene'}]\n",
        "        ],\n",
        "        subplot_titles=titles,\n",
        "        horizontal_spacing=0.02,\n",
        "        vertical_spacing=0.05\n",
        "    )\n",
        "\n",
        "    layout_updates = {\n",
        "        'autosize': True,\n",
        "        'height': 1300,\n",
        "        'showlegend': False,\n",
        "        'paper_bgcolor': '#000000',\n",
        "        'plot_bgcolor': '#000000',\n",
        "        'font': dict(color='#ffffff', family='system-ui'),\n",
        "        'margin': dict(l=0, r=0, b=0, t=60),\n",
        "        'title': dict(\n",
        "            text=\"🌐 <b>KHÂU 3: BẢNG TIẾN TRÌNH HUẤN LUYỆN 3D GAUSSIAN POINT CLOUDS (6 MỐC ITERATIONS)</b>\",\n",
        "            x=0.01, y=0.995,\n",
        "            font=dict(size=17, color='#38bdf8')\n",
        "        )\n",
        "    }\n",
        "\n",
        "    for idx, it in enumerate(iters):\n",
        "        row = (idx // 2) + 1\n",
        "        col = (idx % 2) + 1\n",
        "        if it in ply_cache:\n",
        "            vertex, total_pts = ply_cache[it]\n",
        "            x = np.asarray(vertex['x'], dtype=np.float32)\n",
        "            y = np.asarray(vertex['y'], dtype=np.float32)\n",
        "            z = np.asarray(vertex['z'], dtype=np.float32)\n",
        "\n",
        "            # Giải mã màu RGB từ Spherical Harmonics f_dc_0, f_dc_1, f_dc_2\n",
        "            names = [p.name for p in vertex.properties]\n",
        "            if 'f_dc_0' in names and 'f_dc_1' in names and 'f_dc_2' in names:\n",
        "                f_dc_0 = np.asarray(vertex['f_dc_0'], dtype=np.float32)\n",
        "                f_dc_1 = np.asarray(vertex['f_dc_1'], dtype=np.float32)\n",
        "                f_dc_2 = np.asarray(vertex['f_dc_2'], dtype=np.float32)\n",
        "                SH_C0 = 0.28209479177387814\n",
        "                r = np.clip(0.5 + SH_C0 * f_dc_0, 0.0, 1.0)\n",
        "                g = np.clip(0.5 + SH_C0 * f_dc_1, 0.0, 1.0)\n",
        "                b = np.clip(0.5 + SH_C0 * f_dc_2, 0.0, 1.0)\n",
        "            elif 'red' in names and 'green' in names and 'blue' in names:\n",
        "                r = np.asarray(vertex['red'], dtype=np.float32)\n",
        "                g = np.asarray(vertex['green'], dtype=np.float32)\n",
        "                b = np.asarray(vertex['blue'], dtype=np.float32)\n",
        "                if r.max() > 1.0:\n",
        "                    r, g, b = r / 255.0, g / 255.0, b / 255.0\n",
        "            else:\n",
        "                r = g = b = np.ones_like(x) * 0.8\n",
        "\n",
        "            # Downsample 30,000 điểm cho mỗi ô giúp quan sát rõ nét & mượt 60 FPS\n",
        "            max_pts = 30000\n",
        "            if total_pts > max_pts:\n",
        "                sub_idx = np.random.choice(total_pts, max_pts, replace=False)\n",
        "                x_sub, y_sub, z_sub = x[sub_idx], y[sub_idx], z[sub_idx]\n",
        "                r_sub, g_sub, b_sub = r[sub_idx], g[sub_idx], b[sub_idx]\n",
        "            else:\n",
        "                x_sub, y_sub, z_sub = x, y, z\n",
        "                r_sub, g_sub, b_sub = r, g, b\n",
        "\n",
        "            colors_hex = [f'rgb({int(ri*255)},{int(gi*255)},{int(bi*255)})' for ri, gi, bi in zip(r_sub, g_sub, b_sub)]\n",
        "\n",
        "            fig.add_trace(\n",
        "                go.Scatter3d(\n",
        "                    x=x_sub, y=y_sub, z=z_sub,\n",
        "                    mode='markers',\n",
        "                    marker=dict(size=1.8, color=colors_hex, opacity=0.92),\n",
        "                    name=f'{it:,} Iterations',\n",
        "                    hoverinfo='none'\n",
        "                ),\n",
        "                row=row, col=col\n",
        "            )\n",

        "        scene_key = f\"scene{idx+1}\" if idx > 0 else \"scene\"\n",
        "        layout_updates[scene_key] = dict(\n",
        "            xaxis=dict(visible=False),\n",
        "            yaxis=dict(visible=False),\n",
        "            zaxis=dict(visible=False),\n",
        "            aspectmode='data',\n",
        "            bgcolor='#000000'\n",
        "        )\n",
        "\n",
        "    fig.update_layout(**layout_updates)\n",
        "    print(\"✨ Đã dựng thành công Khung 6 Mây Điểm Khâu 3 (3 Hàng x 2 Cột) Độc Lập To Rõ Nét!\")\n",
        "    fig.show(config={'responsive': True, 'displayModeBar': True})\n",
        "\n",
        "# ── Thực thi hiển thị 6 mây điểm Khâu 3 độc lập ───────────────────────────────\n",
        "display_step3_snapshots_3x2_grid()"
    ]
})

notebook_json = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.10.12"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(notebook_json, f, indent=2, ensure_ascii=False)

shutil.copy2(notebook_path, fix_notebook_path)

print(f"3x2 Large Grid Plotly Notebook written to:\n- {notebook_path}\n- {fix_notebook_path}")
