import os
import json
import shutil

notebook_path = os.path.abspath(os.path.join("notebooks", "point_cloud_interactive_viewer.ipynb"))
fix_notebook_path = os.path.abspath(os.path.join("fix", "point_cloud_interactive_viewer.ipynb"))
os.makedirs(os.path.dirname(notebook_path), exist_ok=True)
os.makedirs(os.path.dirname(fix_notebook_path), exist_ok=True)

cells = []

# Cell 1: Check dependencies
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_01_install_deps",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── Cài Đặt Thư Viện Nạp File PLY ─────────────────────────────────────────────\n",
        "!pip install -q plyfile numpy"
    ]
})

# Cell 2: Khâu 1 Interactive Point Cloud Viewer
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_02_step1_interactive_point_cloud",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── KHÂU 1: Hiển Thị Mây Điểm Ban Đầu (Iter 0) Tương Tác 3D Trực Quan ───────────────\n",
        "import os\n",
        "import base64\n",
        "import numpy as np\n",
        "from plyfile import PlyData\n",
        "from IPython.display import HTML, display\n",
        "\n",
        "def display_interactive_point_cloud(ply_path, max_points=100000, height=650):\n",
        "    \"\"\"\n",
        "    Hiển thị Khung Biểu Diễn Mây Điểm 3D Tương Tác WebGL trong Jupyter Notebook / Google Colab.\n",
        "    - Xoay 360 độ (Trái/Phải/Lên/Xuống), Zoom In/Out (Scroll wheel).\n",
        "    - Nút Play/Pause Tự Động Quay 360 độ quanh hướng camera.\n",
        "    - Thanh trượt tùy chỉnh kích thước điểm (Point Size).\n",
        "    - Nút Căn Giữa (Reset View).\n",
        "    \"\"\"\n",
        "    if not os.path.exists(ply_path):\n",
        "        print(f\"❌ Không tìm thấy file point cloud tại: {ply_path}\")\n",
        "        print(\"👉 Vui lòng kiểm tra lại đường dẫn tới file initial_point_cloud.ply\")\n",
        "        return\n",
        "\n",
        "    print(f\"📂 Đang đọc và xử lý file Mây Điểm: {ply_path} ...\")\n",
        "    plydata = PlyData.read(ply_path)\n",
        "    vertex = plydata['vertex']\n",
        "\n",
        "    x = np.asarray(vertex['x'], dtype=np.float32)\n",
        "    y = np.asarray(vertex['y'], dtype=np.float32)\n",
        "    z = np.asarray(vertex['z'], dtype=np.float32)\n",
        "    positions = np.stack([x, y, z], axis=-1)\n",
        "\n",
        "    names = [p.name for p in vertex.properties]\n",
        "    if 'red' in names and 'green' in names and 'blue' in names:\n",
        "        r = np.asarray(vertex['red'], dtype=np.float32)\n",
        "        g = np.asarray(vertex['green'], dtype=np.float32)\n",
        "        b = np.asarray(vertex['blue'], dtype=np.float32)\n",
        "        if r.max() > 1.0:\n",
        "            r, g, b = r / 255.0, g / 255.0, b / 255.0\n",
        "        colors = np.stack([r, g, b], axis=-1)\n",
        "    elif 'f_dc_0' in names and 'f_dc_1' in names and 'f_dc_2' in names:\n",
        "        f_dc_0 = np.asarray(vertex['f_dc_0'], dtype=np.float32)\n",
        "        f_dc_1 = np.asarray(vertex['f_dc_1'], dtype=np.float32)\n",
        "        f_dc_2 = np.asarray(vertex['f_dc_2'], dtype=np.float32)\n",
        "        SH_C0 = 0.28209479177387814\n",
        "        r = np.clip(0.5 + SH_C0 * f_dc_0, 0.0, 1.0)\n",
        "        g = np.clip(0.5 + SH_C0 * f_dc_1, 0.0, 1.0)\n",
        "        b = np.clip(0.5 + SH_C0 * f_dc_2, 0.0, 1.0)\n",
        "        colors = np.stack([r, g, b], axis=-1)\n",
        "    else:\n",
        "        colors = np.ones_like(positions, dtype=np.float32) * 0.8\n",
        "\n",
        "    total_points = len(positions)\n",
        "    if total_points > max_points:\n",
        "        indices = np.random.choice(total_points, max_points, replace=False)\n",
        "        positions = positions[indices]\n",
        "        colors = colors[indices]\n",
        "\n",
        "    centroid = positions.mean(axis=0)\n",
        "    positions_centered = positions - centroid\n",
        "    max_radius = np.max(np.linalg.norm(positions_centered, axis=1))\n",
        "    if max_radius > 0:\n",
        "        positions_centered = positions_centered / max_radius\n",
        "\n",
        "    pos_b64 = base64.b64encode(positions_centered.astype(np.float32).tobytes()).decode('ascii')\n",
        "    col_b64 = base64.b64encode(colors.astype(np.float32).tobytes()).decode('ascii')\n",
        "    elem_id = abs(hash(ply_path)) % 1000000\n",
        "\n",
        "    html_code = f\"\"\"\n",
        "    <div id=\"pcd-container-{elem_id}\" style=\"position: relative; width: 100%; height: {height}px; background: #0f172a; border-radius: 14px; overflow: hidden; font-family: system-ui, -apple-system, sans-serif; box-shadow: 0 12px 30px -5px rgba(0, 0, 0, 0.6); border: 1px solid rgba(255, 255, 255, 0.1);\">\n",
        "        \n",
        "        <!-- Control Overlay Header -->\n",
        "        <div style=\"position: absolute; top: 16px; left: 16px; z-index: 10; display: flex; gap: 10px; align-items: center; background: rgba(15, 23, 42, 0.85); backdrop-filter: blur(10px); padding: 8px 16px; border-radius: 30px; border: 1px solid rgba(255, 255, 255, 0.15); box-shadow: 0 4px 15px rgba(0,0,0,0.3);\">\n",
        "            <button id=\"btn-play-{elem_id}\" style=\"background: linear-gradient(135deg, #3b82f6, #2563eb); color: white; border: none; padding: 7px 16px; border-radius: 20px; font-weight: 600; font-size: 13px; cursor: pointer; display: flex; align-items: center; gap: 6px; transition: all 0.2s; box-shadow: 0 4px 12px rgba(59, 130, 246, 0.4);\">\n",
        "                <span id=\"play-icon-{elem_id}\">⏸</span> <span id=\"play-text-{elem_id}\">Tự Động Quay 360°</span>\n",
        "            </button>\n",
        "            <button id=\"btn-reset-{elem_id}\" style=\"background: rgba(255, 255, 255, 0.1); color: #e2e8f0; border: 1px solid rgba(255, 255, 255, 0.2); padding: 7px 14px; border-radius: 20px; font-size: 13px; cursor: pointer; transition: all 0.2s;\">\n",
        "                ↺ Căn Giữa\n",
        "            </button>\n",
        "            <div style=\"display: flex; align-items: center; gap: 8px; color: #94a3b8; font-size: 12px; margin-left: 6px;\">\n",
        "                <span>Kích thước điểm:</span>\n",
        "                <input id=\"slider-size-{elem_id}\" type=\"range\" min=\"0.005\" max=\"0.08\" step=\"0.005\" value=\"0.02\" style=\"width: 90px; accent-color: #3b82f6; cursor: pointer;\">\n",
        "            </div>\n",
        "        </div>\n",
        "\n",
        "        <!-- Footer Info Badge -->\n",
        "        <div style=\"position: absolute; bottom: 16px; right: 16px; z-index: 10; background: rgba(15, 23, 42, 0.85); backdrop-filter: blur(10px); color: #cbd5e1; padding: 8px 16px; border-radius: 20px; font-size: 12px; border: 1px solid rgba(255, 255, 255, 0.15);\">\n",
        "            🌐 Khâu 1 Mây Điểm Ban Đầu (Iter 0) | Số điểm: <strong style=\"color: #60a5fa;\">{len(positions):,}</strong> / {total_points:,}\n",
        "        </div>\n",
        "\n",
        "        <div id=\"webgl-canvas-{elem_id}\" style=\"width: 100%; height: 100%;\"></div>\n",
        "    </div>\n",
        "\n",
        "    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js\"></script>\n",
        "    <script src=\"https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/controls/OrbitControls.js\"></script>\n",
        "\n",
        "    <script>\n",
        "    (function() {{\n",
        "        const container = document.getElementById(\"webgl-canvas-{elem_id}\");\n",
        "        const width = container.clientWidth || 800;\n",
        "        const height = container.clientHeight || {height};\n",
        "\n",
        "        const scene = new THREE.Scene();\n",
        "        scene.background = new THREE.Color(0x0f172a);\n",
        "\n",
        "        const camera = new THREE.PerspectiveCamera(45, width / height, 0.1, 100);\n",
        "        camera.position.set(0, 0, 2.8);\n",
        "\n",
        "        const renderer = new THREE.WebGLRenderer({{ antialias: true }});\n",
        "        renderer.setPixelRatio(window.devicePixelRatio);\n",
        "        renderer.setSize(width, height);\n",
        "        container.appendChild(renderer.domElement);\n",
        "\n",
        "        const controls = new THREE.OrbitControls(camera, renderer.domElement);\n",
        "        controls.enableDamping = true;\n",
        "        controls.dampingFactor = 0.05;\n",
        "        controls.autoRotate = true;\n",
        "        controls.autoRotateSpeed = 2.5;\n",
        "\n",
        "        function base64ToFloat32Array(b64) {{\n",
        "            const binary_string = window.atob(b64);\n",
        "            const len = binary_string.length;\n",
        "            const bytes = new Uint8Array(len);\n",
        "            for (let i = 0; i < len; i++) {{\n",
        "                bytes[i] = binary_string.charCodeAt(i);\n",
        "            }}\n",
        "            return new Float32Array(bytes.buffer);\n",
        "        }}\n",
        "\n",
        "        const posArray = base64ToFloat32Array(\"{pos_b64}\");\n",
        "        const colArray = base64ToFloat32Array(\"{col_b64}\");\n",
        "\n",
        "        const geometry = new THREE.BufferGeometry();\n",
        "        geometry.setAttribute('position', new THREE.BufferAttribute(posArray, 3));\n",
        "        geometry.setAttribute('color', new THREE.BufferAttribute(colArray, 3));\n",
        "\n",
        "        const material = new THREE.PointsMaterial({{\n",
        "            size: 0.02,\n",
        "            vertexColors: true,\n",
        "            sizeAttenuation: true,\n",
        "            transparent: true,\n",
        "            opacity: 0.95\n",
        "        }});\n",
        "\n",
        "        const pointCloud = new THREE.Points(geometry, material);\n",
        "        scene.add(pointCloud);\n",
        "\n",
        "        let isAutoRotating = true;\n",
        "        const btnPlay = document.getElementById(\"btn-play-{elem_id}\");\n",
        "        const playIcon = document.getElementById(\"play-icon-{elem_id}\");\n",
        "        const playText = document.getElementById(\"play-text-{elem_id}\");\n",
        "\n",
        "        btnPlay.addEventListener(\"click\", () => {{\n",
        "            isAutoRotating = !isAutoRotating;\n",
        "            controls.autoRotate = isAutoRotating;\n",
        "            if (isAutoRotating) {{\n",
        "                playIcon.innerText = \"⏸\";\n",
        "                playText.innerText = \"Tự Động Quay 360°\";\n",
        "                btnPlay.style.background = \"linear-gradient(135deg, #3b82f6, #2563eb)\";\n",
        "            }} else {{\n",
        "                playIcon.innerText = \"▶\";\n",
        "                playText.innerText = \"Tạm Dừng\";\n",
        "                btnPlay.style.background = \"rgba(255, 255, 255, 0.15)\";\n",
        "            }}\n",
        "        }});\n",
        "\n",
        "        const btnReset = document.getElementById(\"btn-reset-{elem_id}\");\n",
        "        btnReset.addEventListener(\"click\", () => {{\n",
        "            camera.position.set(0, 0, 2.8);\n",
        "            controls.target.set(0, 0, 0);\n",
        "            controls.update();\n",
        "        }});\n",
        "\n",
        "        const sliderSize = document.getElementById(\"slider-size-{elem_id}\");\n",
        "        sliderSize.addEventListener(\"input\", (e) => {{\n",
        "            material.size = parseFloat(e.target.value);\n",
        "        }});\n",
        "\n",
        "        function animate() {{\n",
        "            requestAnimationFrame(animate);\n",
        "            controls.update();\n",
        "            renderer.render(scene, camera);\n",
        "        }}\n",
        "        animate();\n",
        "    }})();\n",
        "    </script>\n",
        "    \"\"\"\n",
        "    display(HTML(html_code))\n",
        "\n",
        "# ── Kiểm Tra và Đường Dẫn Tới File Mây Điểm Khâu 1 (Iter 0) ────────────────────\n",
        "possible_paths = [\n",
        "    \"/content/drive/MyDrive/demo_video_counter/step1_initial_points/initial_point_cloud.ply\",\n",
        "    \"/kaggle/working/demo_video_counter/step1_initial_points/initial_point_cloud.ply\",\n",
        "    \"/kaggle/working/thesis-all/spec-fastgs/datasets/mipnerf360/counter/sparse/0/points3D.ply\",\n",
        "    \"step1_initial_points/initial_point_cloud.ply\"\n",
        "]\n",
        "\n",
        "ply_path = None\n",
        "for p in possible_paths:\n",
        "    if os.path.exists(p):\n",
        "        ply_path = p\n",
        "        break\n",
        "\n",
        "if ply_path:\n",
        "    display_interactive_point_cloud(ply_path)\n",
        "else:\n",
        "    print(\"⚠️ Chưa tìm thấy file initial_point_cloud.ply. Vui lòng chỉ định đường dẫn chính xác tới file .ply!\")"
    ]
})

notebook_json = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.10.12"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(notebook_json, f, indent=2, ensure_ascii=False)

shutil.copy2(notebook_path, fix_notebook_path)

print(f"Interactive Point Cloud Notebook successfully written to:\n- {notebook_path}\n- {fix_notebook_path}")
