import json
import os
import shutil

notebook_path = r"c:\Users\YUT9HC\Desktop\Z\thesis-all\notebooks\kaggle_demo_video_thesis.ipynb"
fix_notebook_path1 = r"c:\Users\YUT9HC\Desktop\Z\thesis-all\fix\video-demo-thesis.ipynb"
fix_notebook_path2 = r"c:\Users\YUT9HC\Desktop\Z\thesis-all\fix\kaggle_demo_video_thesis.ipynb"

cells = []

# Cell 1: Title & Description (Markdown)
cells.append({
    "cell_type": "markdown",
    "id": "cell_01_title",
    "metadata": {},
    "source": [
        "# 🎬 Spec-FastGS Video Demo Generator: Scene 'counter'\n",
        "\n",
        "Notebook này tự động hóa toàn bộ quy trình trích xuất dữ liệu làm **Video Clip Demo** cho đề tài Spec-FastGS trên Kaggle:\n",
        "1. **Khâu 0 (Cấu hình & Chọn Góc Chụp)**: Tự động chọn cố định 10 góc ảnh (10 fixed camera viewpoints) đại diện cho scene `counter`.\n",
        "2. **Khâu 1 (Mây điểm ban đầu - Initial Point Cloud)**: Render và lưu ảnh mây điểm thưa ban đầu (Iteration 0) từ đúng 10 góc chụp cố định.\n",
        "3. **Khâu 2 (Reflection Prior Maps)**: Trích xuất 10 bản đồ Reflection Prior (phương pháp Tan-Ikeuchi) tương ứng với 10 góc chụp.\n",
        "4. **Khâu 3 (Huấn luyện & Capture Snapshots mỗi 5k iter)**: Huấn luyện Spec-fastgs 30.000 iterations, sau mỗi **5.000 iterations** tự động render và lưu 10 khung ảnh từ 10 góc chụp cố định.\n",
        "5. **Khâu 4 (Kết xuất đánh giá cuối cùng Iter 30k)**: Thu thập trọn bộ 4 thư mục kết quả đánh giá (`spec`, `renders`, `gt`, `heatmap`) **chỉ dành riêng cho 10 scenes cố định đã chọn**.\n",
        "6. **Khâu 5 (Tự động Upload Hugging Face)**: Đẩy toàn bộ ảnh, mây điểm và kết quả render lên HuggingFace Dataset: **`DiBiay/video-demo-thesis`**."
    ]
})

# Cell 2: Setup Config Variables (Code)
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_02_config",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── Cấu Hình Biến Môi Trường & Token ────────────────────────────────────────────\n",
        "import os\n",
        "import sys\n",
        "\n",
        "PROJECT_DIR = \"/kaggle/working/thesis-all\"\n",
        "DEMO_OUTPUT_DIR = \"/kaggle/working/demo_video_counter\"\n",
        "HF_REPO_ID = \"DiBiay/video-demo-thesis\"\n",
        "\n",
        "# Tự động đọc HF_TOKEN từ Kaggle Secrets nếu có\n",
        "HF_TOKEN = os.environ.get(\"HF_TOKEN\", \"\")\n",
        "if not HF_TOKEN:\n",
        "    try:\n",
        "        from kaggle_secrets import UserSecretsClient\n",
        "        user_secrets = UserSecretsClient()\n",
        "        HF_TOKEN = user_secrets.get_secret(\"HF_TOKEN\")\n",
        "    except Exception:\n",
        "        pass\n",
        "\n",
        "# Điền HF Token của bạn tại đây trên Kaggle nếu không dùng Kaggle Secrets\n",
        "if not HF_TOKEN:\n",
        "    HF_TOKEN = \"YOUR_HF_TOKEN\" #@param {type:\"string\"}\n",
        "\n",
        "os.environ[\"HF_TOKEN\"] = HF_TOKEN\n",
        "os.environ[\"HF_HUB_DISABLE_SYMLINKS_WARNING\"] = \"1\"\n",
        "\n",
        "os.makedirs(DEMO_OUTPUT_DIR, exist_ok=True)\n",
        "print(f\"✅ Cấu hình hoàn tất!\")\n",
        "print(f\"Thư mục kết quả Demo: {DEMO_OUTPUT_DIR}\")"
    ]
})

# Cell 3: Symlink Dataset & Clone Repo (Code)
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_03_setup_env",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── Clone Repo & Thiết Lập Dataset 'counter' ───────────────────────────\n",
        "import os\n",
        "import shutil\n",
        "\n",
        "REPO_URL = \"https://github.com/0Nguyen0Cong0Tuan0/thesis-all.git\"\n",
        "KAGGLE_INPUT_DATASET = \"/kaggle/input/mipnerf360-dataset\"\n",
        "\n",
        "# Đảm bảo không bị lỗi đã tồn tại folder dở dang khi git clone\n",
        "specfastgs_check = os.path.join(PROJECT_DIR, \"spec-fastgs\")\n",
        "if not os.path.exists(specfastgs_check):\n",
        "    print(f\"📦 Đang clone repository từ {REPO_URL} ...\")\n",
        "    if os.path.exists(PROJECT_DIR) and not os.path.exists(os.path.join(PROJECT_DIR, \".git\")):\n",
        "        shutil.rmtree(PROJECT_DIR, ignore_errors=True)\n",
        "    !git clone --recursive {REPO_URL} \"{PROJECT_DIR}\"\n",
        "else:\n",
        "    print(f\"✅ Repo đã tồn tại tại {PROJECT_DIR}\")\n",
        "\n",
        "# Tạo cấu hình dataset cho scene counter\n",
        "target_scene_dir = os.path.join(PROJECT_DIR, \"spec-fastgs\", \"datasets\", \"mipnerf360\", \"counter\")\n",
        "source_scene_dir = os.path.join(KAGGLE_INPUT_DATASET, \"counter\")\n",
        "\n",
        "os.makedirs(target_scene_dir, exist_ok=True)\n",
        "\n",
        "if os.path.exists(source_scene_dir):\n",
        "    for item in os.listdir(source_scene_dir):\n",
        "        src_item = os.path.join(source_scene_dir, item)\n",
        "        dst_item = os.path.join(target_scene_dir, item)\n",
        "        # 1. Thư mục ảnh (images_8, images_4, images): Tạo Symlink để đọc nhanh\n",
        "        if os.path.isdir(src_item) and item in [\"images_8\", \"images_4\", \"images\"]:\n",
        "            if os.path.lexists(dst_item):\n",
        "                os.remove(dst_item) if not os.path.isdir(dst_item) else shutil.rmtree(dst_item)\n",
        "            os.symlink(src_item, dst_item)\n",
        "            print(f\"  -> Created symlink for images: {dst_item} -> {src_item}\")\n",
        "        # 2. Thư mục 'sparse': COPY PHYSICALLY để ghi file points3D.ply vào /kaggle/working mà không bị lỗi Read-only\n",
        "        elif os.path.isdir(src_item) and item == \"sparse\":\n",
        "            if os.path.lexists(dst_item):\n",
        "                os.remove(dst_item) if not os.path.isdir(dst_item) else shutil.rmtree(dst_item)\n",
        "            shutil.copytree(src_item, dst_item)\n",
        "            print(f\"  -> Physically copied 'sparse' folder to writable location: {dst_item}\")\n",
        "        elif os.path.isfile(src_item):\n",
        "            if not os.path.exists(dst_item):\n",
        "                shutil.copy2(src_item, dst_item)\n",
        "    print(\"✅ Thiết lập Dataset cho scene 'counter' thành công!\")\n",
        "else:\n",
        "    print(f\"❌ Không tìm thấy scene 'counter' trong {KAGGLE_INPUT_DATASET}\")"
    ]
})

# Cell 4: Install Dependencies & Compile Submodules (Code)
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_04_compile_submodules",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── Cài Đặt Official COLMAP Binary (từ colmap/colmap) & Thư Viện Phụ Thuộc ────────\n",
        "!apt-get update -qq && apt-get install -y -qq colmap\n",
        "!colmap --help > /dev/null && echo \"✅ Official COLMAP binary successfully installed!\"\n",
        "!pip install -q plyfile tqdm websockets openpyxl pandas ninja huggingface_hub\n",
        "\n",
        "import torch\n",
        "print(f\"CUDA Available: {torch.cuda.is_available()}\")\n",
        "if torch.cuda.is_available():\n",
        "    print(f\"Active GPU: {torch.cuda.get_device_name(0)}\")\n",
        "\n",
        "# Tự động thiết lập CUDA toolkit\n",
        "cuda_dirs = [\"/usr/local/cuda\", \"/usr/local/cuda-12.2\", \"/usr/local/cuda-12.1\", \"/usr/local/cuda-12\", \"/usr/local/cuda-11.8\"]\n",
        "detected_cuda = None\n",
        "for d in cuda_dirs:\n",
        "    if os.path.exists(os.path.join(d, \"bin\", \"nvcc\")):\n",
        "        detected_cuda = d\n",
        "        break\n",
        "if detected_cuda:\n",
        "    os.environ[\"CUDA_HOME\"] = detected_cuda\n",
        "    os.environ[\"PATH\"] = f\"{detected_cuda}/bin:\" + os.environ.get(\"PATH\", \"\")\n",
        "    os.environ[\"LD_LIBRARY_PATH\"] = f\"{detected_cuda}/lib64:\" + os.environ.get(\"LD_LIBRARY_PATH\", \"\")\n",
        "    print(f\"Configured CUDA: {detected_cuda}\")\n",
        "\n",
        "submodules_dir = os.path.join(PROJECT_DIR, \"FastGS_backup_v2\", \"submodules\")\n",
        "if os.path.exists(submodules_dir):\n",
        "    !cd \"{submodules_dir}/diff-gaussian-rasterization_fastgs\" && pip install -q .\n",
        "    !cd \"{submodules_dir}/simple-knn\" && pip install -q .\n",
        "    !cd \"{submodules_dir}/fused-ssim\" && pip install -q .\n",
        "    print(\"🎉 Biên dịch và nạp CUDA Submodules thành công!\")"
    ]
})

# Cell 5: Select 10 Fixed Views & Step 1: Render Initial Point Cloud (Code)
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_05_step1_initial_points",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── KHÂU 0 & KHÂU 1: Chạy COLMAP Tạo Mây Điểm Ban Đầu & Render 10 Góc Chụp (Iter 0) ───\n",
        "import os\n",
        "import sys\n",
        "import json\n",
        "import torch\n",
        "import subprocess\n",
        "import shutil\n",
        "from PIL import Image\n",
        "\n",
        "os.environ[\"QT_QPA_PLATFORM\"] = \"offscreen\"\n",
        "\n",
        "specfastgs_path = os.path.abspath(os.path.join(PROJECT_DIR, \"spec-fastgs\"))\n",
        "if not os.path.exists(specfastgs_path):\n",
        "    raise RuntimeError(f\"❌ Không tìm thấy thư mục spec-fastgs tại {specfastgs_path}. Vui lòng chạy lại Cell 3 (git clone).\")\n",
        "\n",
        "if specfastgs_path not in sys.path:\n",
        "    sys.path.insert(0, specfastgs_path)\n",
        "os.chdir(specfastgs_path)\n",
        "\n",
        "source_path = os.path.join(specfastgs_path, \"datasets\", \"mipnerf360\", \"counter\")\n",
        "step1_dir = os.path.join(DEMO_OUTPUT_DIR, \"step1_initial_points\")\n",
        "demo_model_path = os.path.join(PROJECT_DIR, \"spec-fastgs\", \"output\", \"demo_counter\")\n",
        "os.makedirs(step1_dir, exist_ok=True)\n",
        "os.makedirs(demo_model_path, exist_ok=True)\n",
        "\n",
        "# 1. Tái tạo Mây Điểm Ban Đầu (Sparse Point Cloud) bằng COLMAP từ tập ảnh đầu vào\n",
        "colmap_db = os.path.join(source_path, \"database.db\")\n",
        "images_dir = os.path.join(source_path, \"images_8\")\n",
        "if not os.path.exists(images_dir):\n",
        "    images_dir = os.path.join(source_path, \"images\")\n",
        "\n",
        "print(f\"🌐 Đang chạy COLMAP tái tạo mây điểm từ tập ảnh đầu vào: {images_dir} ...\")\n",
        "colmap_env = os.environ.copy()\n",
        "colmap_env[\"QT_QPA_PLATFORM\"] = \"offscreen\"\n",
        "\n",
        "try:\n",
        "    if os.path.exists(colmap_db):\n",
        "        os.remove(colmap_db)\n",
        "    print(\"  [1/3] Trích xuất SIFT features (CPU mode for headless server)...\")\n",
        "    subprocess.run([\n",
        "        \"colmap\", \"feature_extractor\",\n",
        "        \"--database_path\", colmap_db,\n",
        "        \"--image_path\", images_dir,\n",
        "        \"--ImageReader.single_camera\", \"1\",\n",
        "        \"--SiftExtraction.use_gpu\", \"0\"\n",
        "    ], env=colmap_env, check=True)\n",
        "    print(\"  [2/3] Ghép nối features (Exhaustive Matcher)...\")\n",
        "    subprocess.run([\n",
        "        \"colmap\", \"exhaustive_matcher\",\n",
        "        \"--database_path\", colmap_db,\n",
        "        \"--SiftMatching.use_gpu\", \"0\"\n",
        "    ], env=colmap_env, check=True)\n",
        "    print(\"  [3/3] Dựng mây điểm thưa 3D (COLMAP Mapper)...\")\n",
        "    sparse_output = os.path.join(source_path, \"sparse\")\n",
        "    os.makedirs(os.path.join(sparse_output, \"0\"), exist_ok=True)\n",
        "    subprocess.run([\n",
        "        \"colmap\", \"mapper\",\n",
        "        \"--database_path\", colmap_db,\n",
        "        \"--image_path\", images_dir,\n",
        "        \"--output_path\", sparse_output,\n",
        "        \"--Mapper.ba_global_function_tolerance\", \"0.000001\"\n",
        "    ], env=colmap_env, check=True)\n",
        "    print(\"✅ COLMAP tái tạo Mây Điểm Ban Đầu (Sparse Point Cloud) thành công!\")\n",
        "except Exception as e:\n",
        "    print(f\"⚠️ Lưu ý khi chạy COLMAP tái tạo mây điểm: {e}\")\n",
        "    print(\"👉 Sử dụng mây điểm sẵn có trong thư mục sparse writable để tiếp tục render.\")\n",
        "\n",
        "# 2. Khởi tạo cấu hình GaussianModel & Scene\n",
        "from argparse import ArgumentParser\n",
        "from scene import Scene, GaussianModel\n",
        "from arguments import ModelParams, PipelineParams\n",
        "from gaussian_renderer import render_fastgs\n",
        "\n",
        "arg_parser = ArgumentParser(description=\"Demo video initial points renderer\")\n",
        "lp = ModelParams(arg_parser, sentinel=True)\n",
        "pp = PipelineParams(arg_parser)\n",
        "parsed_args = arg_parser.parse_args([\"-s\", source_path, \"-m\", demo_model_path, \"-i\", \"images_8\", \"--sh_degree\", \"3\", \"--asg_degree\", \"24\", \"--resolution\", \"-1\", \"--eval\"])\n",
        "dataset = lp.extract(parsed_args)\n",
        "pipe = pp.extract(parsed_args)\n",
        "\n",
        "gaussians = GaussianModel(dataset.sh_degree, dataset.asg_degree)\n",
        "scene = Scene(dataset, gaussians, load_iteration=None, shuffle=False)\n",
        "\n",
        "test_cameras = scene.getTestCameras()\n",
        "num_cams = len(test_cameras)\n",
        "print(f\"Tổng số camera test khả dụng trong scene 'counter': {num_cams}\")\n",
        "\n",
        "# Chọn 10 góc ảnh phân bố đều\n",
        "selected_indices = [int(i * (num_cams - 1) / 9) for i in range(10)]\n",
        "selected_cameras = [test_cameras[idx] for idx in selected_indices]\n",
        "selected_cam_names = [cam.image_name for cam in selected_cameras]\n",
        "\n",
        "# Lưu thông tin 10 góc camera chọn cố định\n",
        "fixed_cams_path = os.path.join(DEMO_OUTPUT_DIR, \"fixed_cameras.json\")\n",
        "with open(fixed_cams_path, \"w\", encoding=\"utf-8\") as f:\n",
        "    json.dump({\"selected_indices\": selected_indices, \"camera_names\": selected_cam_names}, f, indent=4)\n",
        "\n",
        "print(f\"✅ Đã chọn cố định 10 góc chụp camera: {selected_cam_names}\")\n",
        "\n",
        "# Render mây điểm ban đầu (Iteration 0)\n",
        "bg_color = torch.tensor([0, 0, 0], dtype=torch.float32, device=\"cuda\")\n",
        "\n",
        "print(\"🎨 Đang render và lưu 10 ảnh mây điểm thưa ban đầu (Khâu 1)...\")\n",
        "with torch.no_grad():\n",
        "    for i, cam in enumerate(selected_cameras):\n",
        "        render_pkg = render_fastgs(cam, gaussians, pipe, bg_color, 1.0)\n",
        "        img_tensor = render_pkg[\"render\"].clamp(0.0, 1.0)\n",
        "        img_np = (img_tensor.detach().permute(1, 2, 0).cpu().numpy() * 255).astype(\"uint8\")\n",
        "        out_file = os.path.join(step1_dir, f\"view_{i+1:02d}_{cam.image_name}.png\")\n",
        "        Image.fromarray(img_np).save(out_file)\n",
        "        print(f\"  -> Đã lưu Khâu 1 ảnh {i+1}/10: {out_file}\")\n",
        "\n",
        "# 3. Lưu lại file Mây Điểm Ban Đầu (Point Cloud Iteration 0)\n",
        "initial_ply_path = os.path.join(step1_dir, \"initial_point_cloud.ply\")\n",
        "gaussians.save_ply(initial_ply_path)\n",
        "print(f\"💾 Đã lưu file Mây Điểm Ban Đầu (Point Cloud Iter 0): {initial_ply_path}\")\n",
        "\n",
        "print(\"✅ Khâu 1 hoàn tất!\")"
    ]
})

# Cell 6: Step 2: Extract & Save 10 Reflection Prior Maps (Code)
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_06_step2_reflection_prior",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── KHÂU 2: Trích Xuất & Lưu 10 Bản Đồ Reflection Prior (Tan-Ikeuchi) ────────────────\n",
        "import os\n",
        "import sys\n",
        "import json\n",
        "import shutil\n",
        "import subprocess\n",
        "\n",
        "source_path = os.path.join(PROJECT_DIR, \"spec-fastgs\", \"datasets\", \"mipnerf360\", \"counter\")\n",
        "step2_dir = os.path.join(DEMO_OUTPUT_DIR, \"step2_reflection_priors\")\n",
        "os.makedirs(step2_dir, exist_ok=True)\n",
        "\n",
        "# 1. Chạy script trích xuất reflection prior theo phương pháp Tan-Ikeuchi\n",
        "print(\"🔍 Đang chạy trích xuất Reflection Prior bản đồ bóng (Tan-Ikeuchi)...\" )\n",
        "cmd = [\n",
        "    sys.executable, \"extract_reflection_prior.py\",\n",
        "    \"-s\", source_path,\n",
        "    \"-i\", \"images_8\",\n",
        "    \"--ref_prior_method\", \"tan\"\n",
        "]\n",
        "subprocess.run(cmd, cwd=os.path.join(PROJECT_DIR, \"spec-fastgs\"), check=True)\n",
        "\n",
        "# 2. Đọc lại danh sách 10 camera cố định từ Khâu 0\n",
        "fixed_cams_path = os.path.join(DEMO_OUTPUT_DIR, \"fixed_cameras.json\")\n",
        "with open(fixed_cams_path, \"r\", encoding=\"utf-8\") as f:\n",
        "    cam_data = json.load(f)\n",
        "selected_cam_names = cam_data[\"camera_names\"]\n",
        "\n",
        "prior_dir = os.path.join(source_path, \"reflection_prior\")\n",
        "\n",
        "print(\"📸 Đang trích xuất và sao chép 10 bản đồ Reflection Prior tương ứng...\")\n",
        "for i, cam_name in enumerate(selected_cam_names):\n",
        "    prior_file = os.path.join(prior_dir, f\"{cam_name}_ref_score.png\")\n",
        "    if not os.path.exists(prior_file):\n",
        "        prior_file = os.path.join(prior_dir, f\"{cam_name}.png\")\n",
        "    if not os.path.exists(prior_file):\n",
        "        prior_file = os.path.join(prior_dir, f\"{cam_name}.jpg\")\n",
        "        \n",
        "    if os.path.exists(prior_file):\n",
        "        out_file = os.path.join(step2_dir, f\"view_{i+1:02d}_{cam_name}_prior.png\")\n",
        "        shutil.copy2(prior_file, out_file)\n",
        "        print(f\"  -> Đã lưu Khâu 2 Prior {i+1}/10: {out_file}\")\n",
        "    else:\n",
        "        print(f\"  ⚠️ Cảnh báo: Không tìm thấy prior cho camera {cam_name} tại {prior_file}\")\n",
        "\n",
        "print(\"✅ Khâu 2 hoàn tất!\")"
    ]
})

# Cell 7: Step 3: Train 30k Iterations & Capture 10 Views Every 5,000 Iterations (Code)
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_07_step3_train_snapshots",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── KHÂU 3: Huấn Luyện 30k Iterations & Snapshots 10 Góc Chụp Mỗi 5.000 Iterations ────\n",
        "import os\n",
        "import sys\n",
        "import subprocess\n",
        "\n",
        "source_path = os.path.join(PROJECT_DIR, \"spec-fastgs\", \"datasets\", \"mipnerf360\", \"counter\")\n",
        "model_path = os.path.join(PROJECT_DIR, \"spec-fastgs\", \"output\", \"demo_counter\")\n",
        "step3_dir = os.path.join(DEMO_OUTPUT_DIR, \"step3_training_snapshots\")\n",
        "os.makedirs(step3_dir, exist_ok=True)\n",
        "\n",
        "env = os.environ.copy()\n",
        "env[\"DEMO_SNAPSHOT_DIR\"] = step3_dir\n",
        "env[\"DEMO_SNAPSHOT_INTERVAL\"] = \"5000\"\n",
        "\n",
        "print(f\"🏋️ Khởi động huấn luyện Spec-fastgs 30.000 iterations trên scene 'counter'...\")\n",
        "print(f\"Cấu hình: Render & lưu 10 góc ảnh snapshot sau mỗi 5.000 iterations (5k, 10k, 15k, 20k, 25k, 30k)\")\n",
        "\n",
        "cmd = [\n",
        "    sys.executable, \"train.py\",\n",
        "    \"-s\", source_path,\n",
        "    \"-m\", model_path,\n",
        "    \"-i\", \"images_8\",\n",
        "    \"--eval\",\n",
        "    \"--iterations\", \"30000\",\n",
        "    \"--densification_interval\", \"100\",\n",
        "    \"--optimizer_type\", \"default\",\n",
        "    \"--asg_degree\", \"64\",\n",
        "    \"--is_real\", \"--is_indoor\",\n",
        "    \"--sh_degree\", \"3\",\n",
        "    \"--highfeature_lr\", \"0.02\",\n",
        "    \"--grad_abs_thresh\", \"0.0004\",\n",
        "    \"--specular_start_iter\", \"3000\",\n",
        "    \"--ref_prior_method\", \"tan\",\n",
        "    \"--sh_spec_grad_scale\", \"0.75\",\n",
        "    \"--sh_spec_mask_start\", \"8000\",\n",
        "    \"--sh_spec_mask_threshold\", \"0.75\",\n",
        "    \"--sh_spec_min_metric_count\", \"2\",\n",
        "    \"--use_ref_score\", \"--use_adaptive_prior\", \"--use_sh_spec_mask\"\n",
        "]\n",
        "\n",
        "subprocess.run(cmd, cwd=os.path.join(PROJECT_DIR, \"spec-fastgs\"), env=env, check=True)\n",
        "print(\"✅ Khâu 3 hoàn tất!\")"
    ]
})

# Cell 8: Step 4: Render & Filter Exactly 10 Scenes for 4 Folders (spec, renders, gt, heatmap) (Code)
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_08_step4_render_final_eval",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── KHÂU 4: Kết Xuất Cuối Cùng (Iter 30k) Cho 10 Scenes Cố Định (spec, renders, gt, heatmap) ────\n",
        "import os\n",
        "import sys\n",
        "import json\n",
        "import shutil\n",
        "import subprocess\n",
        "\n",
        "source_path = os.path.join(PROJECT_DIR, \"spec-fastgs\", \"datasets\", \"mipnerf360\", \"counter\")\n",
        "model_path = os.path.join(PROJECT_DIR, \"spec-fastgs\", \"output\", \"demo_counter\")\n",
        "step4_dir = os.path.join(DEMO_OUTPUT_DIR, \"step4_final_eval_results\")\n",
        "os.makedirs(step4_dir, exist_ok=True)\n",
        "\n",
        "# 1. Chạy render.py để xuất các ảnh đánh giá\n",
        "print(\"🎨 Đang chạy render.py để kết xuất ảnh đánh giá cuối cùng (Iteration 30,000)...\" )\n",
        "render_cmd = [\n",
        "    sys.executable, \"render.py\",\n",
        "    \"-s\", source_path,\n",
        "    \"-m\", model_path,\n",
        "    \"-i\", \"images_8\",\n",
        "    \"--eval\",\n",
        "    \"--asg_degree\", \"64\",\n",
        "    \"--is_real\", \"--is_indoor\",\n",
        "    \"--ref_prior_method\", \"tan\",\n",
        "    \"--use_ref_score\", \"--use_adaptive_prior\", \"--use_sh_spec_mask\"\n",
        "]\n",
        "\n",
        "subprocess.run(render_cmd, cwd=os.path.join(PROJECT_DIR, \"spec-fastgs\"), check=True)\n",
        "\n",
        "# 2. Đọc danh sách 10 góc camera chọn cố định\n",
        "fixed_cams_path = os.path.join(DEMO_OUTPUT_DIR, \"fixed_cameras.json\")\n",
        "with open(fixed_cams_path, \"r\", encoding=\"utf-8\") as f:\n",
        "    cam_data = json.load(f)\n",
        "\n",
        "selected_cams = cam_data.get(\"camera_names\", [])\n",
        "selected_indices = cam_data.get(\"selected_indices\", [])\n",
        "print(f\"📷 Danh sách 10 camera cố định: {selected_cams}\")\n",
        "\n",
        "# 3. Khởi tạo 4 thư mục spec, renders, gt, heatmap dành riêng cho 10 scenes\n",
        "folders = [\"spec\", \"renders\", \"gt\", \"heatmap\"]\n",
        "for f_name in folders:\n",
        "    sub_dir = os.path.join(step4_dir, f_name)\n",
        "    if os.path.exists(sub_dir):\n",
        "        shutil.rmtree(sub_dir)\n",
        "    os.makedirs(sub_dir, exist_ok=True)\n",
        "\n",
        "ours_30000_dir = os.path.join(model_path, \"test\", \"ours_30000\")\n",
        "\n",
        "if os.path.exists(ours_30000_dir):\n",
        "    print(\"📦 Đang trích xuất và lọc chính xác 10 scenes cho 4 thư mục (spec, renders, gt, heatmap)...\" )\n",
        "    \n",
        "    for i, cam_name in enumerate(selected_cams):\n",
        "        prefix = f\"view_{i+1:02d}_{cam_name}\"\n",
        "        idx_str = f\"{selected_indices[i]:05d}\" if i < len(selected_indices) else \"\"\n",
        "        \n",
        "        # --- a) Lọc Renders cho 10 Scenes ---\n",
        "        src_renders = os.path.join(ours_30000_dir, \"renders\")\n",
        "        if os.path.exists(src_renders):\n",
        "            for fname in os.listdir(src_renders):\n",
        "                if cam_name in fname or (idx_str and fname.startswith(idx_str)):\n",
        "                    shutil.copy2(os.path.join(src_renders, fname), os.path.join(step4_dir, \"renders\", f\"{prefix}.png\"))\n",
        "                    break\n",
        "\n",
        "        # --- b) Lọc Ground Truth cho 10 Scenes ---\n",
        "        src_gt = os.path.join(ours_30000_dir, \"gt\")\n",
        "        if os.path.exists(src_gt):\n",
        "            for fname in os.listdir(src_gt):\n",
        "                if cam_name in fname or (idx_str and fname.startswith(idx_str)):\n",
        "                    shutil.copy2(os.path.join(src_gt, fname), os.path.join(step4_dir, \"gt\", f\"{prefix}.png\"))\n",
        "                    break\n",
        "\n",
        "        # --- c) Lọc Specular Component cho 10 Scenes ---\n",
        "        src_spec = os.path.join(ours_30000_dir, \"spec\")\n",
        "        if os.path.exists(src_spec):\n",
        "            found_spec = False\n",
        "            for fname in os.listdir(src_spec):\n",
        "                if (cam_name in fname or (idx_str and fname.startswith(idx_str))) and (\"only_asg\" in fname or \"spec\" in fname):\n",
        "                    shutil.copy2(os.path.join(src_spec, fname), os.path.join(step4_dir, \"spec\", f\"{prefix}_spec.png\"))\n",
        "                    found_spec = True\n",
        "                    break\n",
        "            if not found_spec:\n",
        "                for fname in os.listdir(src_spec):\n",
        "                    if cam_name in fname or (idx_str and fname.startswith(idx_str)):\n",
        "                        shutil.copy2(os.path.join(src_spec, fname), os.path.join(step4_dir, \"spec\", f\"{prefix}_spec.png\"))\n",
        "                        break\n",
        "\n",
        "        # --- d) Lọc Heatmap cho 10 Scenes ---\n",
        "        src_heatmap = os.path.join(ours_30000_dir, \"heatmap\")\n",
        "        if os.path.exists(src_heatmap):\n",
        "            for fname in os.listdir(src_heatmap):\n",
        "                if cam_name in fname or (idx_str and fname.startswith(idx_str)):\n",
        "                    shutil.copy2(os.path.join(src_heatmap, fname), os.path.join(step4_dir, \"heatmap\", f\"{prefix}_heatmap.png\"))\n",
        "                    break\n",
        "\n",
        "    for f_name in folders:\n",
        "        count = len(os.listdir(os.path.join(step4_dir, f_name)))\n",
        "        print(f\"  -> Thư mục '{f_name}': {count}/10 ảnh scenes đã được lọc thành công.\")\n",
        "        \n",
        "    print(f\"✅ Khâu 4 hoàn tất: Đã tạo đúng 10 scenes cho cả 4 thư mục (spec, renders, gt, heatmap) tại {step4_dir}!\")\n",
        "else:\n",
        "    print(f\"⚠️ Cảnh báo: Không tìm thấy thư mục kết quả render tại {ours_30000_dir}\")"
    ]
})

# Cell 9: Step 5: Upload Everything to Hugging Face Dataset (Code)
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "id": "cell_09_upload_huggingface",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── KHÂU 5: Upload Tự Động Toàn Bộ Kết Quả Lên HuggingFace Dataset ─────────────────\n",
        "import os\n",
        "import time\n",
        "from huggingface_hub import HfApi\n",
        "\n",
        "HF_REPO_ID = \"DiBiay/video-demo-thesis\"\n",
        "DEMO_OUTPUT_DIR = \"/kaggle/working/demo_video_counter\"\n",
        "HF_TOKEN = os.environ.get(\"HF_TOKEN\", \"\")\n",
        "\n",
        "if not HF_TOKEN or HF_TOKEN == \"YOUR_HF_TOKEN\":\n",
        "    try:\n",
        "        from kaggle_secrets import UserSecretsClient\n",
        "        user_secrets = UserSecretsClient()\n",
        "        HF_TOKEN = user_secrets.get_secret(\"HF_TOKEN\")\n",
        "    except Exception:\n",
        "        pass\n",
        "\n",
        "if not HF_TOKEN or HF_TOKEN == \"YOUR_HF_TOKEN\":\n",
        "    print(\"⚠️ Cảnh báo: Chưa cấu hình HF_TOKEN hợp lệ. Vui lòng điền token của bạn vào form Cell 2 hoặc thêm Kaggle Secrets 'HF_TOKEN'.\")\n",
        "else:\n",
        "    print(f\"☁️ Đang tải toàn bộ thư mục demo ({DEMO_OUTPUT_DIR}) lên HuggingFace Repo: {HF_REPO_ID} ...\")\n",
        "    api = HfApi(token=HF_TOKEN)\n",
        "    api.create_repo(repo_id=HF_REPO_ID, repo_type=\"dataset\", exist_ok=True)\n",
        "    \n",
        "    # 1. Kích hoạt Git LFS cho file binary .ply, .bin, .pth, .png trên Hugging Face Repo\n",
        "    gitattr_text = \"*.ply filter=lfs diff=lfs merge=lfs -text\\n*.bin filter=lfs diff=lfs merge=lfs -text\\n*.pth filter=lfs diff=lfs merge=lfs -text\\n*.zip filter=lfs diff=lfs merge=lfs -text\\n\"\n",
        "    local_gitattr = os.path.join(DEMO_OUTPUT_DIR, \".gitattributes\")\n",
        "    with open(local_gitattr, \"w\", encoding=\"utf-8\") as f:\n",
        "        f.write(gitattr_text)\n",
        "    \n",
        "    try:\n",
        "        api.upload_file(\n",
        "            path_or_fileobj=gitattr_text.encode(\"utf-8\"),\n",
        "            path_in_repo=\".gitattributes\",\n",
        "            repo_id=HF_REPO_ID,\n",
        "            repo_type=\"dataset\"\n",
        "        )\n",
        "        print(\"✅ Đã thiết lập Git LFS (.gitattributes) trên Hugging Face Repo!\")\n",
        "    except Exception as git_err:\n",
        "        print(f\"⚠️ Cấu hình .gitattributes: {git_err}\")\n",
        "    \n",
        "    # 2. Upload toàn bộ thư mục kết quả (chứa step1, step2, step3, step4_final_eval_results)\n",
        "    for attempt in range(3):\n",
        "        try:\n",
        "            api.upload_folder(\n",
        "                folder_path=DEMO_OUTPUT_DIR,\n",
        "                path_in_repo=\"counter_demo_video\",\n",
        "                repo_id=HF_REPO_ID,\n",
        "                repo_type=\"dataset\"\n",
        "            )\n",
        "            print(f\"🎉 CHÚC MỪNG! Đã upload thành công toàn bộ dữ liệu Video Demo & Render 10 Scenes (spec, renders, gt, heatmap) lên Hugging Face!\")\n",
        "            print(f\"👉 Link Dataset: https://huggingface.co/datasets/{HF_REPO_ID}\")\n",
        "            break\n",
        "        except Exception as e:\n",
        "            print(f\"⚠️ Thử lại lần {attempt+1}: Lỗi khi upload: {e}\")\n",
        "            time.sleep(10)"
    ]
})

# Construct Notebook JSON
notebook_json = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.10.12"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

for path in [notebook_path, fix_notebook_path1, fix_notebook_path2]:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(notebook_json, f, ensure_ascii=False, indent=1)

print("Kaggle Demo Video Notebook rebuild complete!")
